### ISSUE TITLE
[CI] Disable CodeQL for changes only on YAML

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1047]
**Describe the bug**
CodeQL takes a long time to run, and has no meaningful output when changes are only done on YAML or MD. 

Using `paths-ignore` doesn't quite work, because this will result in a stalemate situation where the check is Required to run, but never does. It doesn't seem to be "skipped",

One solution is maybe to create a job as a pre-step that exits early when the diff context (somewhat dificult to grab) is only YAML or MD

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by asraa** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by ianlewis** [comment]
> https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

So the solution is ...
> "You can fix this by creating a generic workflow, with the same name,"

I suppose that both workflows with the same name will always run but if one of them fails then the required check fails? Feels like a strange way to solve this issue.

**Comment by ianlewis** [comment]
We should also ignore CodeQL changes when we are only changing markdown docs as well.

**Comment by ianlewis** [comment]
> Since the no-op one always succeeds, the only one that can fail is the original, but it shouldn't run due to paths-ignore. Weirdly enough the PR test I have still hangs on expected/waiting, despite the names of the workflows and jobs to be identical.

I believe this is happening because the protected branch expects "checks" to be posted by the workflow. In the case of our no-op the checks aren't posted. I think we need to require the "CodeQL / Analyze" job to run successfully rather than require checks to be posted.

required status checks on protected branches is really strange UX

**Comment by asraa** [comment]
Thanks Ian! That was helpful. I just re-enabled it after the PR merge to allow for "any source" rather than the github scanning tool. I *think* that addresses that issue. Check me on it if needed

**Comment by ianlewis** [comment]
Unfortunately it looks like that's not working... I think it still expects scanning results, just from "any" source but our no-op doesn't post any.

We can add the "Analyze" job to the required checks and I think that's the right solution, but the current Analyze job step is a matrix strategy which translates to a "Analyze ([language])" job name like "Analyze (go)". It's so annoying that GitHub uses the job names for this.
