### ISSUE TITLE
[feature] pin action by release tag

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1084]
A few internal Action need to be called with they fully fully-qualified name: ```slsa-framework/slsa-github-generator/.github/actions/name@vX.Y.Z```.

We need to ensure they use the same tag as the release tag for consistency. The pre-release should use:
- dispatch event so that we can run it manually before creating a release tag
- during release, as a final verification. Ideally this one should not fail otherwise we will need to further bump the version, otherwise

We also need to update the documentation in RELEASE.md

**Comment by ianlewis** [comment]
Adding https://github.com/slsa-framework/slsa-github-generator/issues/880#issuecomment-1288220141 here too.

> @laurentsimon We still pin almost all of the actions called from the reusable workflows. For example:
> 
> https://github.com/slsa-framework/slsa-github-generator/blob/ce2408f54c685a307925330e1d9ceda98c853fd8/.github/workflows/generator_generic_slsa3.yml#L71
> 
> Do we want to do a builder checkout for these others besides `secure-download-artifact` too? or is the idea to pin all of these at a release per #1084?

**Comment by laurentsimon** [comment]
Good catch. It was a mistake from me and I forgot to update all the refs. I've sent https://github.com/slsa-framework/slsa-github-generator/pull/1126 to fix it. PTAL

**Comment by ianlewis** [comment]
@mchmarny Which references are you referring to. We actually recommend referencing our reusable workflows by tag rather than digest. There is some info on that here: https://github.com/slsa-framework/slsa-github-generator#referencing-slsa-builders-and-generators

**Comment by mchmarny** [comment]
Will take a look, but building provenance of an image based on its tag undermines the integrity of that provenance as the image tag is not guaranteed to be constant and that reference is not cryptographically verifiable in any meaningful way.

**Comment by ianlewis** [comment]
> In example under that link. Pinning by tag causes CodeQL errors being reported on the repo.

I'm not sure I follow. AFAIK CodeQL doesn't report errors on GitHub actions. Can you point me to where the errors are showing up?

**Comment by mchmarny** [comment]
It maybe scorecard, codeql, or even serif report from trivy, all push alert into the security panel in the repo. All of mine are resolved right now and I'm on mobile, but will try to reproduce tomorrow. Should be as simple as referencing it by canonical version and pushing new PR in a repo that's using the SLSA reusable workflow. Example here github.con/mchmarny/s3cme

**Comment by ianlewis** [comment]
Yes, scorecard does produce scanning results for pinned dependencies. Unfortunately we're at the mercy of how GitHub Actions works in this regard. If we pin our reusable workflow my hash, we can't easily verify that the hash used corresponds to a particular release or branch of the slsa-github-generator repository.

**Comment by ianlewis** [comment]
I believe this is fixed since we have updated RELEASE.md to update references, we have [`pre-release/references.sh`](https://github.com/slsa-framework/slsa-github-generator/blob/ad5c0dd4e70e4fab86ad4ee5d424ed6d7b7c7601/.github/workflows/scripts/pre-release/references.sh) checks at pre-release, and [`pre-submit.actions/references.sh`](https://github.com/slsa-framework/slsa-github-generator/blob/ad5c0dd4e70e4fab86ad4ee5d424ed6d7b7c7601/.github/workflows/scripts/pre-submit.actions/references.sh)
