### ISSUE TITLE
Entrypoint is the workflow name

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#11]
At it stands the provenance `invocation.entryPoint` is set to the `workflow` field from the Github Actions workflow. This is the name of the calling workflow or the path if the name is not set.

This seems wrong to me. I think the path to the calling workflow yaml file would be more useful but I'm not sure. We could get from `event.workflow` in the github context.

**Comment by ianlewis** [comment]
Reopening because we can't rely on `workflow` in the event payload as it's not present for all event types.
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads

We'll need to figure out a different way to get the path to the user workflow. The only thing I can thing of right now is checking out the user repository and looking for the `github.workflow` name in the workflow yaml files.

i.e.
```
if github.workflow is a path:
  use github.workflow as the entrypoint
else
  check out the user repository
  search all workflow yaml files for the workflow name in github.workflow

**Comment by ianlewis** [comment]
I created a pending topic on github.community to see if there is a way to reliably get the workflow path but I wonder if there aren't other avenues to submit feature requests.

**Comment by ianlewis** [comment]
In testing the workflow names can be the same for multiple workflows in the same repo so the workflow name by itself won't uniquely identify the workflow being run.

**Comment by ianlewis** [comment]
It seem you can query the action run via Github with the run ID and get the workflow path from there.
https://github.com/check-spelling/check-spelling/blob/c35bc3130c33b27843dd0b0f36be8f1d00b6d126/unknown-words.sh#L279-L292

via:
https://github.community/t/getting-the-path-to-user-workflow-yaml-from-reusable-workflow/250514

**Comment by ianlewis** [comment]
The relevant docs for the API endpoints are here
https://docs.github.com/en/rest/actions/workflow-runs#get-a-workflow-run
https://docs.github.com/en/rest/actions/workflows#get-a-workflow

Not sure yet how authentication with the API would work since I'm pretty sure you need some kind of auth or permissions to read them.

**Comment by joshuagl** [comment]
> Not sure yet how authentication with the API would work since I'm pretty sure you need some kind of auth or permissions to read them.

GitHub Actions have `GITHUB_TOKEN` that can be used to make authenticated API calls: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by laurentsimon** [comment]
neat solution! You can use the gh CLI to play with it too (set GH_TOKEN=__THE_TOKEN__ to make it work non-interactively)

**Comment by ianlewis** [comment]
Yeah, I've since written something and got it working. It requires adding `action` scope to the workflow but otherwise seems to work ok. The token is also present in the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) so that's the one I'm actually using.
https://github.com/slsa-framework/slsa-github-generator/compare/main...ianlewis:workflow-path

I don't really like where the API is going adding parameters to functions and such so I'm trying a refactor in https://github.com/slsa-framework/slsa-github-generator/pull/47 which should hopefully be a bit easier to work with and not create lots of backwards incompatibilities over time. It should also address some of the thoughts @laurentsimon had on #13. I'll try to add more info to the PR there to make it more clear how it's supposed to work before un-drafting it, but feel free to comment early if you have thoughts.
