### ISSUE TITLE
[docs] More explicit instructions for verifying provenance content

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1186]
We include examples of the provenance format in the docs but when generating an `.intoto.jsonl` file the provenance is wrapped in a DSSE envelope and base64 encoded so it's not totally clear how to view it.

We should provide a simple command users can run on the file to view the provenance json.

**Comment by laurentsimon** [comment]
why is the slsa-verifier not enough? Encouraging users to extract information without verification seems dangerous. The `--print-provenance` option is for this use case. Wdut?

**Comment by laurentsimon** [comment]
I see what you mean, thanks for the clarification. Please send us a PR, and link to the DSSE format repository if users want more information.
@ianlewis @diogoteles08  do you agree that tweaking the docs without providing a command to extract the info is enough?

**Comment by diogoteles08** [comment]
Giving that the command is simple and short, I would show the command and link to the docs.
I'll create the PR like this and then we see if it becomes too verbose, OK?

**Comment by ianlewis** [comment]
Yeah, I just imagined adding something like `cat artifact.intoto.jsonl | jq -r '.payload' | base64 -d | jq` to the docs.
