### ISSUE TITLE
[feature] Builder ref in documentation should match the latest stable release

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1188]
We have struggled to keep the ref of the builder in the documentation in sync with the latest stable builder we'd like people to use.

Let's:
1. Add it to RELEASE.md process
2. Add an automated pre-release test to verify the refs are set properly. We do already have some pre-release tests but not for docs (https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/release.yml#L19)

**Comment by laurentsimon** [comment]
@asraa shall we resolve this issue before cutting a new builder release?

**Comment by pnacht** [comment]
I've written up a PR that adds this check. However, I'm OOO right now, will submit it once I get back!

**Comment by asraa** [comment]
SG, thanks @pnacht
