### ISSUE TITLE
[feature] Restore CodeQL to doc-only commits

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1261]
Currently we don't run CodeQL for PRs and commits that are only *.md or *.y(a)ml files. However, [scorecard dings us](https://api.securityscorecards.dev/projects/github.com/slsa-framework/slsa-github-generator) for not running CodeQL on all of our commits.

Should we just run CodeQL on all of our commits so we can improve our scorecard score?

Related #547

**Comment by ianlewis** [comment]
Related https://github.com/ossf/scorecard/issues/2487

**Comment by asraa** [comment]
Oof, I see. That's kinda unfortunate. At this point maybe it's OK since it's unlikely we'll have to move as quick on the doc-only changes. It'd be nice to see if the scorecard issue has any movement, but in the meantime, we can re-enable and see how annoying it gets?

**Comment by ianlewis** [comment]
I think I'll just leave this issue open for now.
1. It's nice to get PR checks to complete quickly.
1. It doesn't ding us too bad. Just a 7/10 for one sub-score.
1. It's not actually an security issue but an issue with the tool.
1. We already have a reasonably high score: 9.0, and still have room for improvement elsewhere.
