### ISSUE TITLE
Update Go builder to latest version of library

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#130]
Related #67

**Comment by ianlewis** [comment]
@laurentsimon We should probably discuss whether it's worth it to continue to have a separate go.mod for the Go builder. I think we addressed privacy by adding it to `internal` and I'm doubtful the Go builder will have significantly more dependencies than the base library, but I'd like your thoughts.

In the future, I can definitely see us having a separate go.mod for a Docker builder (e.g. #23). For example, if we need to import Docker client that would import a huge number of transient dependencies.

**Comment by laurentsimon** [comment]
Let's merge the go.mod, there does not seem to be a simple solution to this at the moment. We can re-visit later if this becomes an issue.
Thanks @ianlewis and @asraa for bringing this up

**Comment by laurentsimon** [comment]
I needed this as part of https://github.com/slsa-framework/slsa-github-generator/pull/142, so I made the changes in the PR
