### ISSUE TITLE
Update starter workflows

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1302]
We have not updated the starter workflows for the [Generic Generator](https://github.com/actions/starter-workflows/blob/main/ci/generator-generic-ossf-slsa3-publish.yml) and [Go builder](https://github.com/actions/starter-workflows/blob/main/ci/go-ossf-slsa3-publish.yml) for a while...

**Comment by ianlewis** [comment]
Added to the container milestone because we released v1.4.0 which means we need to update the starter workflows.

**Comment by mihaimaruseac** [comment]
I think this is now done via https://github.com/actions/starter-workflows/pull/1884

**Comment by asraa** [comment]
Thank you!!
