### ISSUE TITLE
Use ratchet for managing pinned dependencies.

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#134]
Use https://github.com/sethvargo/ratchet for managing pinned dependencies in actions.

**Comment by laurentsimon** [comment]
Let's use dependabot https://github.com/slsa-framework/slsa-github-generator/pull/136

@ianlewis anything Rachet would do we cannot do with dependabot?

**Comment by laurentsimon** [comment]
Actually I'd like to try using renovatebot. It seems to have a few interesting features, one being that versions of pinned dependencies are updated as comment.

@MarkLodato could you install https://github.com/apps/forking-renovate on this repo? It seems to need org-owner approval.

**Comment by ianlewis** [comment]
@laurentsimon I wasn't sure dependabot would help with hashes for Github actions and such that we reference in our workflows. AFAIK, actions and such aren't generally going to be in vuln databases either.

We do want to use dependabot for our Go dependencies etc. though.

**Comment by ianlewis** [comment]
I didn't realize that dependabot would work for github actions too. I think we can try this for now.

**Comment by laurentsimon** [comment]
I'd like to try out renovatebot. We need @MarkLodato LGTM to install the GH app on the repo, though
