### ISSUE TITLE
Replace any testdata from personal repos with example-package testadata

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#137]
From this directory https://github.com/slsa-framework/slsa-github-generator/tree/dc15f82c63a7c87294491c8f5c99f0e7e6451317/internal/builders/go/testdata

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2420848406
Workflow name: go schedule main SLSA3 config-ldflags-main-dir
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/
Trigger: schedule
Branch: main
Date: Wed Jun  1 10:27:44 UTC 2022

**Comment by laurentsimon** [comment]
@asraa let's do this for v1.1.0

**Comment by asraa** [comment]
I think this is done, no more references to laurentsimon's personal repo :)
