### ISSUE TITLE
[bug] signing container returned the UNAUTHORIZED error

### ISSUE THREAD

**Issue by vincentgoat** [slsa-framework/slsa-github-generator#1398]
**Describe the bug**

Login was passed but signing container returned the error:
```
Error: signing docker.io/xxx/admission@sha256:xxx: POST https://index.docker.io/v2/xxx/admission/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:xxx/admission Type:repository] map[Action:push Class: Name:xxx/admission Type:repository]]
```
May I ask why and how to solve it?

**To Reproduce**

Here is my workflow: https://github.com/vincentgoat/kubeedge/actions/runs/3747732410/jobs/6364385682

**Comment by vincentgoat** [comment]
I make a mistake with the registry user name, and I will try it again.

**Comment by laurentsimon** [comment]
Is it working after you've changed the username?

**Comment by vincentgoat** [comment]
Yes, thanks.
By the way, how can I field username with secrets.USERNAME other than github.actor?

**Comment by ianlewis** [comment]
> Yes, thanks. By the way, how can I field username with secrets.USERNAME other than github.actor?

@vincentgoat You can see a workaround here: https://github.com/slsa-framework/slsa-github-generator/issues/1347#issuecomment-1349197971. Please follow that issue for updates.

**Comment by ianlewis** [comment]
@vincentgoat Thanks for the issue. I think this particular issue is resolved so I'll close it. Remaining issues with using secrets for the registry username can be tracked on #1347. Feel free to reopen if you think there are other issues that still need to be addressed.
