### ISSUE TITLE
Rename go builder type

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#141]
We're still using [slsa-github-generator-go](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/pkg/provenance.go#L33): shall we change it to `slsa-github-generator`? 

Wdut @ianlewis @asraa

**Comment by laurentsimon** [comment]
@MarkLodato what would you suggest?

**Comment by ianlewis** [comment]
I think adding `/go` at the end would work? We probably want to differentiate the different builders.
so `https://github.com/slsa-framework/slsa-github-generator/go@v1

**Comment by laurentsimon** [comment]
I'm struggling to see the difference between this type and the `path_to_reusable_workflow.yml@v1.2.3`, for example, which identifies the builder uniquely.

**Comment by laurentsimon** [comment]
I'll make the change to `https://github.com/slsa-framework/slsa-github-generator/go@v1`

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2419091764
Workflow name: go schedule main SLSA3 adversarial build
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/
Trigger: schedule
Branch: main
Date: Wed Jun  1 03:32:29 UTC 2022

**Tests are passing now. Closing this issue.**
