### ISSUE TITLE
[feature] Add more adversarial tests for verify-token Action

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1419]
These can be added in the schedule.e2e.verify-token.default.yml workflow, or directly as unit tests written in typescript.

**Comment by laurentsimon** [comment]
I think this is resolved. @asraa @ianlewis anything in mind that I may be glossing over?

**Comment by ianlewis** [comment]
I think this is ok. `e2e.verify-token.schedule.yml` was expanded since this issue was created. If we find other specific tests we should add then we can create new issues for them.
