### ISSUE TITLE
[verify-token] Allow SLSA v1.0 output option for predicate.

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1483]
**Is your feature request related to a problem? Please describe.**
Currently #1477 implements predicate output in SLSA v0.2 format. When BYO complete, work on an output of the SLSA v1.0 format as well.

We can add an input option that the builders can toggle for output v0.2 and v1.0 and eventually deprecate v0.2

cc @laurentsimon

**Comment by asraa** [comment]
> If v1.0 is released in Feb, could we target it without the need to support v0.2?

I think we should target to make the official release v1.0

I can update the PR to do the v1.0 draft, but I was going with consistency with other builders with v0.2. But maybe we don't need to do that.

**Comment by laurentsimon** [comment]
I think it would reduce technical debt and maintenance if we could jump straight to v1.0. That's my main reasoning. This was we can also focus our effort on v1.0 and support it the day it's announced :)
Wdut?

**Comment by asraa** [comment]
> That's my main reasoning. This way we can also focus our effort on v1.0 and support it the day it's announced :)

Let's do it! It'll help move the effort for v1.0 along. Let's say it's happening soon and it will.

I'll update the PR in a few hours.
