### ISSUE TITLE
Attestation upload is broken

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#149]
I was testing something, and came across the following error (expect the e2e tests to trigger a bunch of similar issues within 24hr):

`uploading attestation: &{0 } (*models.Error) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface` https://github.com/slsa-framework/example-package/runs/6694426603?check_suite_focus=true

Error coming from https://github.com/slsa-framework/slsa-github-generator/blob/main/signing/sigstore/rekor.go#L53

@asraa @ianlewis any ideas what's going on?

**Comment by bobcallaway** [comment]
can you run it again with `DEBUG=1` on (assuming this is using `rekor-cli` or our client libs?

**Comment by laurentsimon** [comment]
what is it only happening today "deterministically" :-)

**Comment by laurentsimon** [comment]
Rekor team fixed it yesterday. Closing.
