### ISSUE TITLE
[feature] harden file writes

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1513]
The builders take untrusted path from projects and use them to create files. We do have code in place to detect directory traversal, but it's easy to forget to use the functions. Directory traversals don't remove all risks, because a project could attempt to overwrite an existing file that belongs to the builder.
I would like to propose to harden our implementation the following way:
1. create a file, say `safe-file.[go|ts]`. 

Have a 
```
func safeFileWrite() error{
  verifyDirTraversal()
  writeIfNotExits()
}
```

2. All file writes should use this function in the code
3. Add pre-submit to verify that only the safe-file directly calls the language-specific `fs.Write()`.

NOTE: the above is similar to what we do in the workflow: all download must use `secure-artifact-download` and we have pre-submit in place to verify it.

**Comment by laurentsimon** [comment]
We should also capture `read` and `mkdir`.
I'll wait for https://github.com/slsa-framework/slsa-github-generator/pull/1557/ to land first

**Comment by ianlewis** [comment]
> We should also capture `read` and `mkdir`. I'll wait for #1557 to land first

We could just forbid other modules from importing `fs` and have the hardened module proxy any file system interactions. That's probably the easiest thing to check for anyway.

**Comment by laurentsimon** [comment]
Sounds like a good idea to catch all fs calls, so long as we don't need other functions like "isFilePresent", etc.
I'll wait to be sure https://github.com/slsa-framework/slsa-github-generator/pull/1612/files works properly, since it's the same pattern we need here to share a module. @asraa I think you ran into problems when trying to share a module: remember what the problems were?

**Comment by ianlewis** [comment]
> Sounds like a good idea to catch all fs calls, so long as we don't need other functions like "isFilePresent", etc.

If we do, we can always just create a proxy function to `fs.isFilePresent` in the "approved" module.

> @asraa I think you ran into problems when trying to share a module: remember what the problems were?

I think she mentioned something about her local setup. I'll take a look at it tomorrow and see if I can't get it working since she'll be off for the next week.
