### ISSUE TITLE
[feature] SLSA v0.2 support for npm builder

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1521]
Due to the timeline of when the npm SLSA RFC will be implemented it's likely we'll need support for SLSA v0.2 in the npm builder. Is that the case?

Currently we are supporting only v1.0 in the [BYOB Framework](https://github.com/slsa-framework/slsa-github-generator/milestone/11) but we may need to support v0.2 as well?

/cc @asraa @laurentsimon

**Comment by asraa** [comment]
I'm sort of leaning towards adding back that option as a top-level workflow input (that we can remove if needed). It may mean running on both formats, but it would be nice to test our slsa-verifier using the existing 0.2 code while we write the BYO framework.

**Comment by laurentsimon** [comment]
I'm onboard with having support for both, especially since npm will be using v0.2, IIUC.
We could also restrict which repos are allowed to use the option  (as be part of the slsa-token?). This way we avoid having others use it.

**Comment by laurentsimon** [comment]
@feelepxyz@github.com @kommendorkapten we'd love your inputs.

**Comment by kommendorkapten** [comment]
We are targeting v1.0 spec version of SLSA for GA, but it's a moving target...
If BYOB for npm would only support v1.0, my view is that it would be totally acceptable.

**Comment by feelepxyz** [comment]
I would love to see npm only support slsa 1.0 for new packages when we launch this publicly by end of this quarter. We're ready to add support as soon as the spec is finalised. If we can get our hands on this by march we should be good.

Npm will still need to support 0.2 provenance statements that have already been created but would simplify some bits if we can narrow down what is supported for new packages.

**Comment by ianlewis** [comment]
@feelepxyz @kommendorkapten Thanks for the comments. Am I right in assuming then that you'll be generating SLSA proveance v0.2 before v1.0 is ready and not provenance based on the [draft version of the v1.0 spec](https://github.com/slsa-framework/slsa/pull/525)? Is it likely that the GA would block on SLSA v1.0 support? or would you roll out with v0.2 if SLSA v1.0's finalization is delayed?

**Comment by kommendorkapten** [comment]
@ianlewis yes, we are using v0.2 right now in development. Yeah, if SLSA v1.0 is delayed, I don't think we would block. It's not my call to make, but that is my guess.

**Comment by ianlewis** [comment]
Fixed by #1827
