### ISSUE TITLE
Use go-githubactions

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#153]
https://github.com/sethvargo/go-githubactions does a lot of the same stuff as the `github` package but does many things better.

For example, it gets github context values via the [built-in environment variables](
https://github.com/sethvargo/go-githubactions/blob/main/actions.go#L455-L501) rather than requiring it be serialized to json and added to a `GITHUB_CONTEXT` environment variable. This is desirable because the `github` context [doesn't seem to be available](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions) inside of an `actions.yml` so it can't be used by reusable actions.

Open issues:
- [x] Does the `GITHUB_EVENT_PATH` method work inside reusable workflows? - Yes
- [x] `GithubContext` needs a way to get the repository. (https://github.com/sethvargo/go-githubactions/pull/46)
- [x] Several other fields are missing from `GithubContext` that are present in [our version](https://github.com/ianlewis/slsa-github-generator/blob/main/github/workflow.go#L28-L48). Some of these fields we may not be using but some others may need to be added. (https://github.com/sethvargo/go-githubactions/pull/46)
  - `ref_type`
  - `base_ref`
  - `head_ref`
  - `run_attempt`

**Comment by laurentsimon** [comment]
Do we need this dependency? If we can easily implement the same, I'd say we avoid adding yet another dependency to manage. In general, in the builder, we should minimize dependencies as much as possible.

Wdut?

**Comment by ianlewis** [comment]
go-githubactions [depends](https://github.com/sethvargo/go-githubactions/blob/main/go.mod) only on [go-envconfig](https://github.com/sethvargo/go-envconfig/blob/main/go.mod) which has essentially no dependencies so transients should be minimal. I'd kind of prefer using it because it would require a lot of manual code to get context from env vars and it pretty much does exactly what we want.

It also does a couple other things nicely like dealing with newlines when writing output commands.

**Comment by ianlewis** [comment]
It's also @sethvargo so I'm reasonably confident in the management of both packages.

**Comment by ianlewis** [comment]
I'll look a bit more into how the `github` context can be used in custom actions in #164 which may make this mute. Removed from the v1 milestone since it's not really ugent.

**Comment by sethvargo** [comment]
@sethvargo? Never heard of 'em 😄

**Comment by ianlewis** [comment]
> @sethvargo? Never heard of 'em 😄

I may have been wrong about Seth's reliability. 😆

**Comment by ianlewis** [comment]
I'm going to close this in favor of #164

**Comment by laurentsimon** [comment]
+1, one less dependency to main and be worried about
