### ISSUE TITLE
[feature] [byo] Add a script that tests the fields of the output SLSA predicate of `verify-token`

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1530]
**Describe the bug**
Add a script that validates the field outputs of the predicate from `verify-token`. It can be similar to https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/scripts/e2e-verify.common.sh adapted for SLSA v1.0

use this in the `verify-token` presubmit schedule test: https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/e2e.verify-token.schedule.yml, and as an example into example-package when we port e2e tests there

**Comment by ianlewis** [comment]
@asraa Feel free to reopen if I'm wrong but I think this is pretty much done?
https://github.com/slsa-framework/slsa-github-generator/blob/4df91f822551fe7916cc7ebc513c8f429fd26181/.github/workflows/scripts/schedule.actions/verify-verified-token.sh
