### ISSUE TITLE
[bug] Unable to authenticate with Google Artifact Registry using Workload Identity

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1545]
Originally posted by @mchmarny
https://github.com/slsa-framework/slsa-github-generator/issues/1257#issuecomment-1384431361

-----

This appears to be also failing against Artifact Registry (full trace for the above error [here](https://github.com/mchmarny/s3cme/actions/runs/3919419059/jobs/6700471398#step:5:700))

```shell
main.go:62: error during command execution: signing us-west1-docker.pkg.dev/cloudy-s3c/s3cme/s3cme@sha256:f17fc9c49e3e1cef22022332c0f55a51d60b12d7403990a6aac6564f4bbd4910: GET https://us-west1-docker.pkg.dev/v2/token?scope=repository%3Acloudy-s3c%2Fs3cme%2Fs3cme%3Apull&service=: DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/cloudy-s3c/locations/us-west1/repositories/s3cme" (or it may not exist)
```

This is despite of the `cosign login` to registry being succesful in the [previous step](https://github.com/mchmarny/s3cme/actions/runs/3919419059/jobs/6700471398#step:4:62)

```shell
login to us-west1-docker.pkg.dev
auth.go:191: logged in via /home/runner/.docker/config.json
```

Also, `cosign attest` (after authentication with the same OIDC token), with the same `predicate.json` file, on the same image, works fine, so the rights of the impersonated service account for which the token was issued are correct. 

```shell
COSIGN_EXPERIMENTAL=1 cosign attest --force --predicate predicate.json --type slsaprovenance $IMG_DIGEST
```

I ended up abandoning this reusable workflow and just [used the released `slsa-github-generator`](https://github.com/mchmarny/s3cme/blob/main/.github/workflows/slsa.yaml) artifact manually (after sha verification). 

FWIW, a Go app repo template with image build/publish pipelines, SBOM, and SLSA provenance (using your `slsa-github-generator`), and OIDC, KMS and Artifact Registry is available in https://github.com/mchmarny/s3cme

**Comment by ianlewis** [comment]
@mchmarny Unfortunately, you can't output a GCP access token from a job as you do [here](https://github.com/mchmarny/s3cme/blob/v0.0.18/.github/workflows/on-tag.yaml#L28) because it gets stripped by GitHub.

You can see that the `access_token` output was ignored in the logs of the `image` job in the "Complete Job" section.
https://github.com/mchmarny/s3cme/actions/runs/3919419059/jobs/6700457948

> Warning: Skip output 'access_token' since it may contain secret.

Since we are using a reusable workflow this kind of precludes us from using access tokens created by the `google-github-actions/auth` action. This is because we have to run the reusable workflow in a separate job and GitHub prevents well-known secrets from being passed between jobs. Currently there is no good way to pass secrets between jobs that I'm aware of.

The only thing that I can think of to do is to add native support for GCP workload identity to the reusable workflow, but I'm really loath to add support for specific registries if I can avoid it.

**Comment by mchmarny** [comment]
I was just looking at this, and pretty much figured the same. 

Passing the provider id and service accounts info between jobs (both not really private or secrets), and then authing inside of each job, while more verbose, does seem to work around that issue. See how I implemented this in [here](https://github.com/mchmarny/s3cme/blob/main/.github/workflows/on-tag.yaml ).

Still, I get a lot of value from the provenance generator binary you publish. And doing the provenance generation inside of [my own reusable workflow](https://github.com/mchmarny/s3cme/blob/dd86e243b0d8fabbabcaed0b9c6669b7bccc1307/.github/workflows/slsa.yaml#L54-L67) gives me more control over the CUE policies later anyway I think. So all good.

**Comment by ianlewis** [comment]
> Passing the provider id and service accounts info between jobs (both not really private or secrets), and then authing inside of each job, while more verbose, does seem to work around that issue. See how I implemented this in [here](https://github.com/mchmarny/s3cme/blob/main/.github/workflows/on-tag.yaml).

Yes. I'd like to support GCP workload identity to avoid special cases in the reusable workflow itself, but we might not be able to avoid adding special support.

As a workaround in the meantime you can also impersonate a service account and store a long-lived access token in GitHub secrets to authenticate with Artifact Registry. 
https://cloud.google.com/artifact-registry/docs/docker/authentication#token

> Still, I get a lot of value from the provenance generator binary you publish. And doing the provenance generation inside of [my own reusable workflow](https://github.com/mchmarny/s3cme/blob/dd86e243b0d8fabbabcaed0b9c6669b7bccc1307/.github/workflows/slsa.yaml#L54-L67) gives me more control over the CUE policies later anyway I think. So all good.

I see that you are verifying the binary checksum, but we generate provenance for all the builder/generator binaries as well so do verify the provenance (at least once for the checksum) so you can be sure they came from us 😄

**Comment by mchmarny** [comment]
> Yes. I'd like to support GCP workload identity to avoid special cases in the reusable workflow itself, but we might not be able to avoid adding special support.

Like I said, authenticating inside of each reusable job, while more verbose, does solves that issue. The auth implementation is specific each OIDC provider so that's the core of the issue here IMO.

> As a workaround in the meantime you can also impersonate a service account and store a long-lived access token in GitHub secrets to authenticate with Artifact Registry.

That's like 10x more complicated than this really needs to be. Also secrets? We have OIDC so we don't have to :) 

Jokes aside, there is a tension between the value of a generic, reusable workflow implementing SLSA, and the boundaries defined by the limitation of reusable workflows (token passing is just one of them).  Given that there are now simple ways to gen the provenance using the binary, there will be cases when it is advisable for people to just write the few lines of YAML and be done. Especially if the entire setup is easy to reproduce like in the [s3cme](https://github.com/mchmarny/s3cme)

**Comment by ianlewis** [comment]
> > Yes. I'd like to support GCP workload identity to avoid special cases in the reusable workflow itself, but we might not be able to avoid adding special support.
> 
> Like I said, authenticating inside of each reusable job, while more verbose, does solves that issue. The auth implementation is specific to each OIDC provider so that's the core of the issue here IMO.
> 
> > As a workaround in the meantime you can also impersonate a service account and store a long-lived access token in GitHub secrets to authenticate with Artifact Registry.
> 
> That's like 10x more complicated than this really needs to be. Also secrets? We have OIDC so we don't have to :)

I'm not sure I agree it's 10x more complicated than workflow identity ([whoo boy](https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)), but I wholeheartedly agree about using OIDC.

> Jokes aside, there is a tension between the value of a generic, reusable workflow implementing SLSA, and the boundaries defined by the limitation of reusable workflows (token passing is just one of them). Given that there are now simple ways to gen the provenance using the binary, there will be cases when it is advisable for people to just write the few lines of YAML and be done. Especially if the entire setup is easy to reproduce like in the [s3cme](https://github.com/mchmarny/s3cme)

Fair enough, though one of the benefits of using a reusable workflow is that the OIDC identity used is that of the reusable workflow and not the user workflow which provides you with an isolated "trusted builder". There is a bit of nuance here but there is some info in our [Threat Model doc](https://github.com/slsa-framework/slsa-github-generator/blob/main/SPECIFICATIONS.md#trusted-builder-and-provenance-generator). This is directly addressing the "[Non-falsifiable provenance](https://slsa.dev/spec/v0.1/requirements#non-falsifiable)" requirement for SLSA 3.
