### ISSUE TITLE
[feature] Repository template for BYOB workflows

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1552]
Since we will expect that BYOB workflows would be in their own repository, we could have a [GitHub repository template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) to help ease adoption.

**Comment by ianlewis** [comment]
@laurentsimon @asraa I'm trying to decide on where to put this repo template? I'm thinking slsa-framework/slsa-github-generator-template

Thoughts?

I have a basic working template here: https://github.com/ianlewis/slsa-byob-template
Still need to update the docs and do some cleanup.

**Comment by asraa** [comment]
+1 on slsa-github-generator-template

I'll read through it pretty soon and file a PR if I have any updates

**Comment by laurentsimon** [comment]
is "generator" too generic? Would this repo contain the docs for everything or just the byob part?

**Comment by asraa** [comment]
I assumed just the BYOB part (like to developers creating their own).

If it's focused on action wrapping, it could be "slsa-action-wrapper-template`

**Comment by ianlewis** [comment]
Yeah. I'm not entirely sure we want to put *all* the BYOB docs there. We may want a proper docs site or something since there is a lot that users would need to understand

**Comment by ianlewis** [comment]
I'll close this once we've moved the template repo to the slsa-framework org.
