### ISSUE TITLE
[feature][byob] fail if the setup-token is called on unsupported event

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1583]
users who try running the code on a PR may silently fail. Maybe pull_request triggers should not not supported, unless debug mode is enabled?

debug mode could also print more logs which would help WRT writers troubleshoot quicker.

**Comment by AdamKorcz** [comment]
To add a few details: The current error response is unrelated to the issue. `setup-token` completes fine, but `verify-token` will subsequently return `Error: Unexpected token P in JSON at position 0`.
