### ISSUE TITLE
[feature] New verify command in the Docker-based builder

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-github-generator#1618]
**Describe the solution you'd like**
Currently to use the Docker-based builder only has `build` and `dry-run` commands that take as input the source, the docker imager, etc. We'd like to have a new command (e.g., `verify`) that takes as input in generated BuildDefinition or provenance, builds the binary the same way the `build` command does, and verifies that the generated binary has the same digest specified in the provenance.

**Describe alternatives you've considered**
Alternatively we could just pass in the BuildDefinition, but that does not contain the binary digest and cannot be used to do a meaningful verification.

**Additional context**
This could be used locally to verify that the provenance generated on GitHub is valid.

**Comment by laurentsimon** [comment]
I'm curious if you want the input to be a provenance file,  in the future?

**Comment by laurentsimon** [comment]
> This could be used locally to verify that the provenance generated on GitHub is valid.

what do you mean by "valid"?
