### ISSUE TITLE
[docs] [BYOB] BYO uploads attestations to rng-slsa-attestations

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1637]
**Describe the bug**
Should the delegator workflow just upload to a fixed output path? 

See example run here: https://github.com/slsa-framework/example-package/actions/runs/4159805591

The outputs are signed - the only complication would be running multiple in parallel, but I wouldn't actually think it is possible to run multiple BYO in parallel (or was it?)

cc @ianlewis @laurentsimon

**Comment by asraa** [comment]
> Did you find problems with the random value?

This is only for the user perspective - seeing XYZ-slsa-attestations for the output is a little strange, but it won't be if we document it and we cleanup the rest of the internal artifacts uploaded.

If so, we can close

**Comment by laurentsimon** [comment]
I'm in favor of cleaning up the artifacts by deleting them, as you proposed; and leave the attestation artifact there.
We can re-visit later, e.g. let users specify the attestation name if they want?

**Comment by laurentsimon** [comment]
We do return the the name of the attestation. What if we asked TRWs to return the name to users as one of their outputs?

**Comment by asraa** [comment]
Good idea! Let's keep these issues open, I'll tag this as a docs issue now.

**Comment by laurentsimon** [comment]
I think this is done. Will add this in doc. Closing. Re-open if you think it is not done.
