### ISSUE TITLE
[feature] [docker] Provenance output name

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1638]
**Is your feature request related to a problem? Please describe.**
Currently the provenance output is uploaded to a folder called `outputs` and then the filename is hardcoded as `attestation1.intoto.sigstore`.  

See this workflow as an example https://github.com/slsa-framework/example-package/actions/runs/4159801908

**Describe the solution you'd like**
I'd like to 
1. Rename the output folder to `slsa-outputs`
2. Cleanup the extraneous files 
3. Rename the filename of the provenance. 

For the final one, we currently use a workflow option `provenance-name` to configure the provenance filename. We may include that here too. Using the `artifact_path` as a default filename is not possible because it may include wildcards.

@rbehjati From a user perspective, what do you think about a default filename? Should we fix it at `attestation.intoto.sigstore`, and allow the user to configure it with a workflow input?

**Comment by rbehjati** [comment]
I think we need to allow the user to specify the name of the provenance. A `provenance-name` workflow option sounds good to me. 

In Oak we generate multiple provenances, and we want to be able to get a separate provenance file for each.
