### ISSUE TITLE
[feature] remove call to getWorkflowRun API

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1643]
The GH env variable contains a `GITHUB_WORKFLOW_REF` `octocat/hello-world/.github/workflows/my-workflow.yml@refs/heads/my_branch`.

I think we can parse this variable to set the workflow https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/verify-token/src/predicate.ts#L146

/cc @asraa

**Comment by ianlewis** [comment]
I'll do this later today.

**Comment by asraa** [comment]
Sweet! I also wasn't sure whether the other env vars were present though

https://github.com/slsa-framework/slsa-github-generator/blob/da4aab2134af8742cf08dbbd352b995edc03cb63/.github/actions/verify-token/src/predicate.ts#L165

**Comment by ianlewis** [comment]
Right. The context object from actions/toolkit includes woefully few values from the context and they are taken from the environment anyway. One of the reasons including the object in the provenance probably isn't all that helpful.

https://github.com/actions/toolkit/blob/d2b7d85e7cb61467395604aae1b84439c320cb84/packages/github/src/context.ts#L40-L52
