### ISSUE TITLE
Usability improvement for input of generic workflow

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#165]
The current input needs:
```
set -euo pipefail
DIGEST=$(sha256sum binary-linux-amd64)
DIGEST="${DIGEST//'%'/'%25'}"
DIGEST="${DIGEST//$'\n'/'%0A'}"
DIGEST="${DIGEST//$'\r'/'%0D'}"
echo "::set-output name=digest::$DIGEST"
```

I wonder whether it'd be easier for users if the input was base64-encoded:
```
set -euo pipefail
DIGEST=$(sha256sum binary-linux-amd64)
DIGESTS=$(echo -n "$DIGEST | base64 -w 0)
echo "::set-output name=digest::$DIGESTS"
```

```
set -euo pipefail
sha256sum binary-linux-amd64 > DIGESTS
sha256sum binary-linux-amd64-2 >> DIGESTS
sha256sum binary-linux-amd64-3 >> DIGESTS
DIGESTS=$(cat DIGESTS | base64 -w 0)
echo "::set-output name=digest::$DIGESTS"
```

I think it's effectively the same, because the string replacements have to be done just once even for multiple digests. If that's the case, we should at least document it. The only reason I'm proposing base64 is that the string substitution may be a little off-putting for some users.

Thoughts?

**Comment by ianlewis** [comment]
Yeah, it's not very user friendly to require users to do it. base64 may be easier for users rather than do the string substitution.

We should probably have friendly error messages if the data isn't properly base64 encoded as well.

**Comment by laurentsimon** [comment]
> Yeah, it's not very user friendly to require users to do it. base64 may be easier for users rather than do the string substitution.

@asraa @MarkLodato @joshuagl wdut?

> We should probably have friendly error messages if the data isn't properly base64 encoded as well.

+1 for this

**Comment by MarkLodato** [comment]
Good idea. That's much better.

I think you can combine it all into a single command?

```bash
echo "::set-output name=digest::$(sha256sum file1 file2 file3 | base64 -w 0)"
```

Or if you prefer a variable:

```bash
FILES=( file1 file2 file3 )
echo "::set-output name=digest::$(sha256sum "${FILES[@]}" | base64 -w 0)"
```

**Comment by ianlewis** [comment]
Another option would be to have them output it with nul terminators instead of newlines (e.g. `sha256sum -z`) but I'm not sure that's easier to understand than using base64
