### ISSUE TITLE
[feature] Update references checks for BYOB

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1681]
Update references checks to check for references to the delegator workflow.

- [pre-release/references.sh](https://github.com/slsa-framework/slsa-github-generator/blob/1ab4b3fedd147dbaa1530ff9c3b59f48ace2bae2/.github/workflows/scripts/pre-release/references.sh)
- [pre-submit.actions/references.sh](https://github.com/slsa-framework/slsa-github-generator/blob/1ab4b3fedd147dbaa1530ff9c3b59f48ace2bae2/.github/workflows/scripts/pre-submit.actions/references.sh)
- [RELEASE.md](https://github.com/slsa-framework/slsa-github-generator/blob/1ab4b3fedd147dbaa1530ff9c3b59f48ace2bae2/RELEASE.md)

**Comment by laurentsimon** [comment]
I think this is already working properly. The scripts search under `.github/workflows/` for the string `slsa-framework/slsa-github-generator/.github/actions/...`, so the delegator workflows will be taken into account.

**Comment by ianlewis** [comment]
Right now I think the scripts miss uses of [delegator_generic_slsa3.yml](https://github.com/slsa-framework/slsa-github-generator/blob/cd68d888a824244d863cc4ba49b17eaa824215b0/.github/workflows/delegator_generic_slsa3.yml).

This will be an issue for any workflows (like the nodejs one) that use BYOB in our repo.
https://github.com/slsa-framework/slsa-github-generator/blob/71cb86986c57cd8173e44c4746c09c3cce7c1c5f/.github/workflows/builder_nodejs_slsa3.yml#L78

**Comment by laurentsimon** [comment]
Got it. I understand what you mean. Agreed.
