### ISSUE TITLE
[feature][byob] Record triggering_actor_id

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1695]
The [SLSA v1.0 RC](https://slsa.dev/github-actions-workflow/v1-rc1#system-parameters) says that the `triggering_actor_id` SHOULD be included in the provenance (if different from the `actor_id`).

I think @MarkLodato generally says fields like this should be left off if they are the same as their "sister" fields (in this case `actor_id`) but is there a reason why we can't just always include it?

Currently the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) doesn't include the `triggering_actor_id`, only the `triggering_actor` which could be reclaimed by another user. I think the only way we can retrieve it is via the [Workflow Run API](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run).

**Comment by MarkLodato** [comment]
> is there a reason why we can't just always include it?

No strong reason. Just to save size and make it a little easier to read since most cases you don't actually care about the triggering actor. But no objections to always recording it.
