### ISSUE TITLE
Drop `.git` in URIs

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa-github-generator#17]
The generated URIs append `.git` to the end, but this is wrong.

```
        "uri": "git+https://github.com/ianlewis/actions-test@refs/heads/main.git",
```

I suggest removing this altogether. (Another option would be to move it before the `@`, but that doesn't seem to have any value.)

**Comment by ianlewis** [comment]
Yeah, I noticed that and was thinking of moving `.git` before the `@` but I couldn't find any good examples of URIs like this. Removing it probably works just as well.
