### ISSUE TITLE
[docs] new `upload-tag-name` feature not documented 

### ISSUE THREAD

**Issue by 34fathombelow** [slsa-framework/slsa-github-generator#1720]
I'm excited to try the new release v1.5.0.  Thanks again for all the hard work you guys continue to do.  

Upon reading the release notes I see there is a new input feature `upload-tag-name` for [Go-builder](https://github.com/slsa-framework/slsa-github-generator/blob/v1.5.0/internal/builders/generic/README.md#workflow-inputs) & [Generic Generator](https://github.com/slsa-framework/slsa-github-generator/blob/v1.5.0/internal/builders/generic/README.md#workflow-inputs).  It appears the README.md for each builder has not been updated to reflect the new inputs.

**Comment by 34fathombelow** [comment]
I'll be happy to submit a PR today to address this.

**Comment by ianlewis** [comment]
@34fathombelow Please do! However, we have an issue for this already #1682. Please feel free to comment there.
