### ISSUE TITLE
[feature] [test] add pull_request_target workflow for verify-token

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1744]
**Is your feature request related to a problem? Please describe.**
A maintainer-triggered pull_request_target workflow for verify-token with OIDC permissions

https://github.com/slsa-framework/slsa-github-generator/pull/1726#issuecomment-1455269281

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by laurentsimon** [comment]
This is now done in the e2e repo. Closing
