### ISSUE TITLE
[feature][nodejs] Use sha512 for subject digest

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#1769]

**Comment by ianlewis** [comment]
It seems that different values are used for integrity checks in `package-lock.json` than by the provenance attestations generated by the npm CLI. I'm not sure how the value for the `package-lock.json` is generated; probably just base64 encoding the binary checksum rather than outputting in hex.

```shell
$ jq '.packages."node_modules/typescript".integrity' < package-lock.json 
"sha512-1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g=="
```

```shell
$ sha512sum ianlewis-actions-test-0.1.25.tgz 
81e128ae7b1ff3bf7f6208bd6f242afe6a586e831c20a88653127e4601ccdc30b1aa73b1d79b6d1791696ab3ff6522131d32ccdfd3165615bda8f6b85f1b6e4a  ianlewis-actions-test-0.1.25.tgz
```

Not a big deal but just noted that since

**Comment by ianlewis** [comment]
> probably just base64 encoding the binary checksum rather than outputting in hex.

Yep.

```shell
$ npm pack --json | jq -r '.[0].integrity' | cut -d'-' -f2 | base64 -d | od -A n -v -t x1 | tr -d ' \n'
81e128ae7b1ff3bf7f6208bd6f242afe6a586e831c20a88653127e4601ccdc30b1aa73b1d79b6d1791696ab3ff6522131d32ccdfd3165615bda8f6b85f1b6e4a

$ sha512sum ianlewis-actions-test-0.1.25.tgz 
81e128ae7b1ff3bf7f6208bd6f242afe6a586e831c20a88653127e4601ccdc30b1aa73b1d79b6d1791696ab3ff6522131d32ccdfd3165615bda8f6b85f1b6e4a  ianlewis-actions-test-0.1.25.tgz

**Comment by laurentsimon** [comment]
There was some discussion in into how to define not just the hash, but also its encoding. It'd be great to be able to have the same string across the lock file and the provenance. Would help readability and incidence response, I think

**Comment by ianlewis** [comment]
I'm not sure how valuable it is to be able to use the same string, and I don't really see base64 encodings of hash checksums that often in the wild but I guess I could be wrong. Might be worth mentioning it.

**Comment by laurentsimon** [comment]
Here's the discussion https://github.com/in-toto/attestation/pull/140/files#r1119009393 on intoto side. Thanks @marcelamelara

**Comment by ianlewis** [comment]
> Here's the discussion https://github.com/in-toto/attestation/pull/140/files#r1119009393 on intoto side. Thanks @marcelamelara

Seems like the consensus was to support one format (lowercase hex) so I'll support that.
