### ISSUE TITLE
[feature] Enable Go Builder to create GitHub Release as a prerelease

### ISSUE THREAD

**Issue by suzuki-shunsuke** [slsa-framework/slsa-github-generator#1795]
**Is your feature request related to a problem? Please describe.**

Currently, Go Builder (builder_go_slsa3.yml) doesn't support creating GitHub Release as a prerelease.
When we publish a prerelease, we have to create GitHub Release once and change it as a prerelease.
It's undesirable.

**Describe the solution you'd like**

Add an input `prerelease` to Reusable workflow to support creating GitHub Release as a prerelase.
If this input is true, GitHub Release is created as a prerelease.
This input is false by default, so the default behaviour isn't changed.

**Describe alternatives you've considered**

I have no idea.

BTW, [GoReleaser supports `auto`](https://goreleaser.com/customization/release/#github).

```yaml
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto
```

This feature is useful. But Go Builder uses [softprops/action-gh-release](https://github.com/softprops/action-gh-release) and this action supports only boolean. So it is difficult to support `auto`.
If we consider supporting `auto` in future, the type of `prerelease` should be `string` rather than `boolean` to keep the compatibility.

**Additional context**

**Comment by asraa** [comment]
Completed in the PR above, thanks!

**Comment by asraa** [comment]
Reopen to track 

- [ ] add 1 e2e test
- [ ] Update the documentation
- [ ] Add a changelog entry

**Comment by asraa** [comment]
Test successful at https://github.com/slsa-framework/example-package/releases/tag/v34.0.1 !
