### ISSUE TITLE
Support `name` containing whitespace

### ISSUE THREAD

**Issue by MarkLodato** [slsa-framework/slsa-github-generator#18]
The current implementation disallows whitespace in the subject `name` because it uses `strings.Fields`. The spec does not disallow whitespace, and spaces in filenames are not uncommon, so it would be best if the implementation allowed that.

To fix, using `strings.Cut` (or `strings.SplitN` or a regexp) would avoid the issue.

**Comment by ianlewis** [comment]
Yeah, that was an oversight. I didn't realize that sha256sum doesn't escape spaces in the name.
