### ISSUE TITLE
[feature] prerelease check list

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1801]
Before releasing this feature e2e tests for prerelease support

- [x] add 1 e2e test
- [ ] Update the documentation
- [ ] Add a changelog entry

**Comment by ianlewis** [comment]
Could we just add this is tasks to complete #1795?

**Comment by asraa** [comment]
e2e test created: https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.go.tag.main.config-ldflags-assets-prerelease-tag.slsa3.yml

**Comment by laurentsimon** [comment]
> e2e test created: https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.go.tag.main.config-ldflags-assets-prerelease-tag.slsa3.yml

do we verify the release is marked pre-release in the verification part?

**Comment by asraa** [comment]
> do we verify the release is marked pre-release in the verification part?

can add that - i just looked at manually but that shouldn't be hard

**Comment by asraa** [comment]
> do we verify the release is marked pre-release in the verification part?

done - https://github.com/slsa-framework/example-package/commit/f19de18c243902859071c2367d06724a292e3081
