### ISSUE TITLE
[feature] SLSA 3 Go Builder add provenance name to the workflow outputs

### ISSUE THREAD

**Issue by developer-guy** [slsa-framework/slsa-github-generator#1842]
**Is your feature request related to a problem? Please describe.**
This is a feature.

**Describe the solution you'd like**

At the time of writing this, SLSA 3 Go Builder does not have the provenance name generated during the workflow within its outputs[^1]. So, it'd be better to provide an output that specifies the provenance name.

**Additional context**
I'm willing to do this, please assign it to me. cc @laurentsimon 

[^1]: https://github.com/slsa-framework/slsa-github-generator/blob/667cb7e0d6b66bd22435d20e23d9ecaf82bd7682/.github/workflows/builder_go_slsa3.yml#L82

**Comment by laurentsimon** [comment]
Let's add e2e tests before closing this issue

**Comment by laurentsimon** [comment]
Added e2e tests in https://github.com/slsa-framework/example-package/commit/7f8f39e9163246e25aecde40ba23e7cecbfacd65. It's using `go-provenance-name` for consistency with the existing `go-binary-name`
