### ISSUE TITLE
[feature] draft releases support for uploading provenance

### ISSUE THREAD

**Issue by developer-guy** [slsa-framework/slsa-github-generator#1862]
**Is your feature request related to a problem? Please describe.**
This might be related to a problem but at the same time, this is a feature.

**Describe the solution you'd like**
While working on the osv-scanner project, I realized that they mark their release as a [draft](https://github.com/google/osv-scanner/blob/284a975e46e674c86547d809d7ecd5b486bfcd61/.goreleaser.yml#L86) for some reason. In that case, if we set the `upload-assets` parameter of the Generic SLSA 3 Generator as true, we see two different releases with the same tag, one is marked as draft the other is marked as latest. Then I dag into the problem a bit, and noticed that the Generic SLSA 3 Generator uses [soft-props/action-gh-release](https://github.com/softprops/action-gh-release) to upload the provenance file, [here](https://github.com/slsa-framework/slsa-github-generator/blob/66b541d35741996cc067fc2a56824c5a37f716ff/.github/workflows/generator_generic_slsa3.yml#L247) and [here](https://github.com/slsa-framework/slsa-github-generator/blob/66b541d35741996cc067fc2a56824c5a37f716ff/.github/workflows/generator_generic_slsa3.yml#L239). There is a draft option available in the [parameters](https://github.com/softprops/action-gh-release#-customizing) of the `action-gh-release` GitHub Action.

So, maybe we can add a new parameter to these generators for people who might want to mark their release as a draft, if so, they can pass that parameter to the `action-gh-release` to avoid having duplicate releases.

PTAL @laurentsimon

**Comment by ianlewis** [comment]
I think this is the same as #1476?  Could you maybe comment on #1476 about osv-scanner?

I'll go ahead and close this and defer to that issue but feel free to re-open if you think there is more that should be covered in a separate issue.
