### ISSUE TITLE
[feature] use search.sigstore.dev as an additional output of the provenance generation

### ISSUE THREAD

**Issue by developer-guy** [slsa-framework/slsa-github-generator#1879]
**Is your feature request related to a problem? Please describe.**
This is a feature and not related to a problem.

**Describe the solution you'd like**
Based on the recent news[^1] that Chainguard contributes the Rekor Search UI project to Sigstore, we might reconsider using this address in one of the outputs about uploading provenance to Rekor.

> This site is now served under: [search.sigstore.dev](https://search.sigstore.dev/)

As of now today, `slsa-github-generator` [outputs](https://github.com/slsa-framework/slsa-github-generator/blob/64fee9e1f91c3423606e50050d7691b738de4403/internal/builders/go/pkg/provenance.go#L190) the following message once it generated provenance:

```bash
Uploaded signed attestation to rekor with UUID 24296fb24b8ad77ad7d75dd8666c9c2d015ef7b498511222851da95142c808257ca7986691f9f38f.
```

From an end-user perspective who might not know how to search this UUID in the transparency log, I thought that we can give information about what would be the next step of using this UUID, for example, we can add an informative message like this:

```bash
You can use rekor-cli to see the log entry details:

$ rekor-cli get --uid 24296fb24b8ad77ad7d75dd8666c9c2d015ef7b498511222851da95142c808257ca7986691f9f38f 

OR

You can use search.sigstore.dev to see the log entry details:

https://search.sigstore.dev/?uuid=24296fb24b8ad77ad7d75dd8666c9c2d015ef7b498511222851da95142c808257ca7986691f9f38f
```

Similar to this issue in Tekton Chains: _https://github.com/tektoncd/chains/issues/576_

[^1]: _https://www.chainguard.dev/unchained/chainguard-contributes-rekor-search-project-to-sigstore_

**Comment by ianlewis** [comment]
@developer-guy Just to be clear, would simply outputting a more informative log message as you described here solve this? or is there some other functionality that's required?

**Comment by developer-guy** [comment]
Yes just outputting a more informative log message would solve this issue ☝️

**Comment by ianlewis** [comment]
> Yes just outputting a more informative log message would solve this issue ☝️

SG. Would be happy to look at a PR for this as well! :)
