### ISSUE TITLE
E2E: Generic push main default SLSA 2

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#190]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2458950626
Workflow name: Generic push main default SLSA 2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.main.default.slsa2.yml
Trigger: push
Branch: main
Date: Wed Jun  8 03:56:33 UTC 2022

**Comment by ianlewis** [comment]
Reopen to let the workflow close it.

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2463091794
Workflow name: Generic push main default SLSA 2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.main.default.slsa2.yml
Trigger: push
Branch: main
Date: Wed Jun  8 17:04:11 UTC 2022

**Tests are passing now. Closing this issue.**
