### ISSUE TITLE
[feature] Add support for gitCommit sha

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1915]
See example https://github.com/slsa-framework/github-actions-buildtypes/blob/main/workflow/v1/example.json#L32
I don't know how we're supposed to differentiate between sha1 and the upcoming sha256...

**Comment by ianlewis** [comment]
> I don't know how we're supposed to differentiate between sha1 and the upcoming sha256...

Maybe create an issue on that repo?

**Comment by laurentsimon** [comment]
done https://github.com/slsa-framework/slsa/issues/797

**Comment by laurentsimon** [comment]
This was implemented for the BYOB in verity-token https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/verify-token/src/predicate1.ts#L100. Closing
