### ISSUE TITLE
[discussion] Reconsider tscommon versioning

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1918]
See comment https://github.com/slsa-framework/slsa-github-generator/pull/1913/files#r1157725414
/cc @ianlewis

**Comment by ianlewis** [comment]
> See comment https://github.com/slsa-framework/slsa-github-generator/pull/1913/files#r1157725414 /cc @ianlewis

SYAC

> Thought about this a bit more. Since we're checking out a single repo, extracting each tarball will fail as soon as we update the code, because each tarball is generated with a different codebase. Do I understand correctly? Maybe using multiple tarballs is adding more complexity that it solves. Let me know, I may be mis-understanding something.

Right. The issue I found is that if you don't run `npm ci` then you don't catch that `tscommon` was updated. But you're comment is right, I think pre-submits would likely catch when the code is updated as integrity checks would fail when running `npm ci`.

**Comment by laurentsimon** [comment]
+1, that's also my understanding.

Let's address https://github.com/slsa-framework/slsa-github-generator/pull/1917#discussion_r1157918002 once this issue resolved.
