### ISSUE TITLE
[feature] Update v1.0 field names

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#1936]
The v0.2 specs used a builder ID, but v1.0 now uses a structure:
```
"builder": {
            "id": old.builder.id,
            "builderDependencies": null,  // not in v0.2
            "version": null,  // not in v0.2
        },
```

`systemParameters` have been renamed to `internalParameters`

https://slsa.dev/provenance/v1-rc2#migrating-from-02

**Comment by ianlewis** [comment]
Do we have any info we would put into the `builderDependencies`?

`version` seems to be a `map (string→string)` and is a "Map of names of components of the build platform to their version". Maybe this is where runner info would go if we include it?

**Comment by laurentsimon** [comment]
Currently we put nothing. We could add image OS and version, I think so. I think builderDeps are low priority

**Comment by laurentsimon** [comment]
Closing this since we have renamed the fields for v1.0.
