### ISSUE TITLE
[bug] Cannot prase provenances produced by the container-based workflow 

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-github-generator#1987]
**Describe the bug**
The signed provenances generated by the [container-based SLSA3 generator](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_docker-based_slsa3.yml) have a different format from the ones generated by the [generic SLSA3 generator](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/generator_generic_slsa3.yml).

This means the tools that parsed and processed the previous no longer work. In particular the DSSE util from https://github.com/secure-systems-lab/go-securesystemslib cannot be used to parse the provenances from the container-based SLSA3 generator.

**To Reproduce**
See the following attached files

[generic-generator.jsonl.txt](https://github.com/slsa-framework/slsa-github-generator/files/11214341/generic-generator.jsonl.txt)
(output of https://github.com/project-oak/oak/actions/runs/4668335201)

[docker-based-generator.intoto.sigstore.txt](https://github.com/slsa-framework/slsa-github-generator/files/11214343/docker-based-generator.intoto.sigstore.txt)
(output of https://github.com/project-oak/oak/actions/runs/4678620661)

**Expected behavior**
I would like to be able to use the DSSE util in https://github.com/secure-systems-lab/go-securesystemslib to parse the provenances. 

Or is there other tools for parsing the new format?

cc @asraa 

**Screenshots**
--

**Additional context**
--

**Comment by asraa** [comment]
Oh, you need to extract the DSSE envelope from the inside - it's contained inside the JSON

```
cat docker-based-generator.intoto.sigstore | jq -r '.dsseEnvelope' 
```

The new output format is based off of the sigstore-protobufs, so that we could now use offline verification.

**Comment by asraa** [comment]
I'll add this to the README.md - this is our new format along with SLSA v1.0 for the docker-based and delegator workflow's that we're creating right now.

**Comment by asraa** [comment]
Check out this helper!

https://github.com/slsa-framework/slsa-verifier/blob/623cf20a23f3360549eafac6efe1a158960f15f9/verifiers/internal/gha/bundle.go#L64-L80

**Comment by rbehjati** [comment]
Thanks. Adding a note to the README would be great. I close this, but feel free to reopen :)
