### ISSUE TITLE
[bug] docker-based workflow broken due to verifier incompatible with #1989

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#1997]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ianlewis** [comment]
Is this breaking the tests or does the builder use the verifier as part of the workflow?

**Comment by ianlewis** [comment]
This is causing the current e2e test failures. 

Currently blocked by https://github.com/slsa-framework/slsa-verifier/issues/561

**Comment by asraa** [comment]
Now that I'm back I can fix the blocker issue by updating to v1.0 provenance
