### ISSUE TITLE
Create provenance generation library

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#2]
Provenance generation can be shared across ecosystems, except for some inputs like `buildConfig` and `parameters` that should be provided by ecosystem-specific builders.

We need to refactor the code we use for https://github.com/slsa-framework/slsa-github-generator-go to use code in this repo (library or CLI)

cc @[ianlewis](https://github.com/ianlewis)

**Comment by laurentsimon** [comment]
I think this issue can be closed, right?

**Comment by ianlewis** [comment]
I'll close it when I merge #47
