### ISSUE TITLE
[feature] Rename the builder_docker-based_slsa3 workflow

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-github-generator#2004]
**Describe the solution you'd like**
We have renamed Docker-based to container-based in the documentation of the [container-based builder](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/docker). For consistency, the [workflow file](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_docker-based_slsa3.yml) should as well be renamed to `builder_container-based_slsa3.yml`.

**Describe alternatives you've considered**
NA

**Additional context**
One should make sure all references to the workflow in e2e tests is updated.

CC @asraa

**Comment by ianlewis** [comment]
Should we update the builder directory name? I think it was renamed to "docker" at some point but I know Go doesn't really like hyphens in package names...
https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders

We can also make sure to update e2e test names and repository issue labels.

**Comment by rbehjati** [comment]
I think `docker` for the directory name is fine, given that (1) there is already a `container` directory, (2) this is `internal` implementation detail. Nevertheless, if you have a good suggestion for the name, I am open to renaming the directory (although I am not sure how wast the impact of this change could be).
