### ISSUE TITLE
[docs][nodejs] Update npm package publishing documentation

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2070]
Update Node.js builder documentation to instruct users on how to publish since the builder will no longer be responsible for publishing.

**Comment by ianlewis** [comment]
We may need to update the doc to include a step to verify the tarball & provenance before running tests or publishing.

@laurentsimon I'm still not sure I understand if we really need this. Even if the tarball was modified, consumers would still catch that the tarball was modified at verification time.  Is this just to catch a modified tarball early to avoid uploading it in the first place (and not rely on any verification done by the npm registry)?

**Comment by laurentsimon** [comment]
Someone may replay old (genuine) provenance / artifacts. Maybe the registry will reject them because the version would already exist.

**Comment by ianlewis** [comment]
> Someone may replay old (genuine) provenance / artifacts. Maybe the registry will reject them because the version would already exist.

Right got it.

**Comment by ianlewis** [comment]
We need to update the docs to remove the inputs for uploading to a release.
