### ISSUE TITLE
[gradle][maven] Remove packages:write from call to lowperms delegator

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2177]
Tracking issue for:
- [ ] https://github.com/slsa-framework/slsa-github-generator/security/code-scanning/521

**Comment by ianlewis** [comment]
Strange, the scorecard issue scanning alert got marked as fixed, but the `packages: write` is still there.
https://github.com/slsa-framework/slsa-github-generator/blob/5b75337ded01fe8282ba78ff61d76957524634da/.github/workflows/builder_gradle_slsa3.yml#L58

**Comment by ianlewis** [comment]
This also seems to be the case for the Maven builder.

**Comment by AdamKorcz** [comment]
Gradle is being done here: https://github.com/slsa-framework/slsa-github-generator/pull/2458

**Comment by AdamKorcz** [comment]
Maven is being done here: https://github.com/slsa-framework/slsa-github-generator/pull/2459
