### ISSUE TITLE
Merge all builder and verifier

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#227]
Shall we merge the builder and verifier repos to make it simpler for users? We could rename this repo `slsa-tools` and have the builders and the verifier.

Some people have told me that a single repo makes it easy for users to discover the project, and for documentation to be in one place (well, we could have a dedicated repo for doc :-))

I don't know what the structure would look like though. Ideally the verifier should be easy to build and install via `go install`, and the generic API should also be easily accessible for public consumption. Yet we want the verifier and generic API to belong to 2 different "projects" to avoid sharing dependencies. Not sure this is feasible, unless the generic API is a private interface :/

Thoughts?

/cc @asraa @ianlewis @MarkLodato @joshuagl

**Comment by ianlewis** [comment]
It may be worth rethinking but I asked this previously and @MarkLodato responded in the negative.

> > Would it also make sense to include the verifier here as well? Might make it easier to manage potential breaking changes if they are both in one repo with one set of pre-submits etc.
> 
> My inclination is no, that is a different use case with different code. Plus, the verifier will hopefully support more than thus this generator in the future.

https://github.com/slsa-framework/slsa-github-generator/issues/36#issuecomment-1110989023

**Comment by laurentsimon** [comment]
gotcha. I don't disagree with this comment. Thanks for linking to the issue, I had forgotten about this part :-)

**Comment by laurentsimon** [comment]
Shall we close this issue?

**Comment by ianlewis** [comment]
Yeah, we can close but lets keep it in the back of our minds as the project develops. I suspect our thinking on this will change over time.
