### ISSUE TITLE
[feature] Allow for running tests with multiple Node.js versions

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2287]
Currently the Node.js builder only supports one Node.js version when running scripts (provided by the `node-version` input).

package maintainers often want to run tests with multiple Node.js versions in order to make sure they are still backwards compatible.

**Comment by ianlewis** [comment]
Maybe the answer is that they just run the tests before calling the builder and the builder just handles running tests?

**Comment by ianlewis** [comment]
@ljharb has a workflow which is convenient for running tests and supports running over multiple Node.js versions. I'm not sure we would really want to implement something similar though.
https://github.com/ljharb/actions/blob/d9f477827ed71a259056764107f74afc29febcae/.github/workflows/node.yml

Example usage:
https://github.com/minimistjs/minimist/blob/fdbb909cf916b3bac9f76f6ee72c64e05b73c2d9/.github/workflows/node-tens.yml#L8-L14

Probably the easiest thing for users to do would be to call ljharb's workflow to run tests and then call ours to do the actual build. I think it makes sense to keep these separate and not implement something specific to running tests.

**Comment by ljharb** [comment]
Especially since the build only needs to be run by the publisher, so there's no reason the build has to have the backwards compatibility support that the production code may need.

**Comment by ianlewis** [comment]
I added some docs with an example of running tests in the builder but I should probably clean that up with an example that runs tests separately.

**Comment by ljharb** [comment]
I also typically run the linter separately, since the linter only needs to run once, while the tests need to run in every supported version (modulo practicality).

**Comment by ianlewis** [comment]
That makes sense. Closing in favor of #2288
