### ISSUE TITLE
[bug] BYOB Workflow failure on slsa-setup

### ISSUE THREAD

**Issue by enteraga6** [slsa-framework/slsa-github-generator#2292]
**Update**
This bug also is appearing on its own when just running a [singular workflow](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272937339/workflow).
[Workflow Error 1](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272925971/jobs/9535768491): `Error: error creating tlog entry`
[Workflow Error 2](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272937339): `Error: error creating signing certificate`

**Describe the bug**
When running two workflows one after another from the same repository, either one of the workflows or both will fail in the slsa-setup stage because of an "error creating signing certificate" or "error creating tlog entry".

Initial Error Message: `Error: error creating signing certificate`

Due to this error message, I believe the bug to be related to Fulcio. [Link to error message output code (sigstore-js file)](https://github.com/sigstore/sigstore-js/blob/8db6c5c953478eddb94c40f3df418f46c211f125/packages/client/src/ca/index.ts#L70)

**To Reproduce**

1. Run this [workflow](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/workflows/runfile-multiple-targets-cc.yml)
2. Wait a second
3. Run this [workflow](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/workflows/runfile-java.yml)
4. See error on slsa-setup on either or both workflows

**Expected behavior**
I expected both workflows to be able to make it past the slsa-setup job.

**Additional context**
Workflow runs where I discovered the bug:
Ran this [first](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272035901) followed by [this](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272039377) next. Bug came on second workflow ran.

Recreated the bug:
This [workflow](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272307643) first followed by this [one](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272308322). Both workflows failed in slsa-setup although different error messages.

cc: @haydentherapper

**Comment by laurentsimon** [comment]
@haydentherapper let us know if you're able to shed some light on what happened. Shall we transfer this issue to the sigstore repo for tracking?

**Comment by enteraga6** [comment]
I opened an Improving Error Message Issue on the sigstore repo: https://github.com/sigstore/sigstore-js/issues/561

**Comment by ianlewis** [comment]
> I opened an Improving Error Message Issue on the sigstore repo: [sigstore/sigstore-js#561](https://github.com/sigstore/sigstore-js/issues/561)

It would be nice if the errors they throw had the cause included in them, but we could check if the error is one of the [error types ](https://github.com/sigstore/sigstore-js/blob/8db6c5c953478eddb94c40f3df418f46c211f125/packages/client/src/sigstore.ts#L116-L121) that sigstore-js exports and print the message for the `cause` as well.

Something like:
```typescript
if (err instanceof sigstore.InternalError) {
    core.setFailed(`${err}: ${err.cause}`);
} else {
    core.setFailed(`${err}`);
}
```

**Comment by haydentherapper** [comment]
I don't have any more information on what could have caused the error. It could have been an intermittent network failure, either in the Sigstore infra or GitHub Actions. I would need a more verbose error message to know why it happened. If you are continuing to get this error, let us know.

**Comment by laurentsimon** [comment]
Thanks @haydentherapper 

@enteraga6 do you want to send a PR t make the fix proposed by @ianlewis in https://github.com/slsa-framework/slsa-github-generator/issues/2292#issuecomment-1592247655?

The code is https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/sign-attestations/src/main.ts#L60-L67. After making the change, `cd .github/actions/sign-attestations && npm run all` to run the linter and compile the typeescript.

**Comment by enteraga6** [comment]
@laurentsimon 

Yes I will! Sorry, I don't know how I missed this! Thanks =)

**Comment by enteraga6** [comment]
@laurentsimon @ianlewis 

PR sent in [here (#2336)](https://github.com/slsa-framework/slsa-github-generator/pull/2336)!

**Comment by laurentsimon** [comment]
Thanks @enteraga6 !
