### ISSUE TITLE
[e2e]: delegator-lowperms release main checkout slsa3 

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2480]
Repo: https://github.com/slsa-framework/example-package/tree/v49.0.1
Run: https://github.com/slsa-framework/example-package/actions/runs/5671341395
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.delegator-lowperms.release.main.checkout.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.delegator-lowperms.release.main.checkout.slsa3.yml
Trigger: release
Branch: v49.0.1
Date: Wed Jul 26 16:33:54 UTC 2023

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v49.0.2
Run: https://github.com/slsa-framework/example-package/actions/runs/5671463438
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.delegator-lowperms.release.main.checkout.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.delegator-lowperms.release.main.checkout.slsa3.yml
Trigger: release
Branch: v49.0.2
Date: Wed Jul 26 16:46:19 UTC 2023

**Comment by laurentsimon** [comment]
Closing manually. Replaced with e2e.delegator-generic.release.main.checkout.slsa3.yml
