### ISSUE TITLE
E2E: Generic (Bazel) tag main default SLSA2

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#253]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.0
Run: https://github.com/slsa-framework/example-package/actions/runs/2480621081
Workflow name: Generic (Bazel) tag main default SLSA2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa2.yml
Trigger: push
Branch: v21.0.0
Date: Sat Jun 11 16:51:59 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.1
Run: https://github.com/slsa-framework/example-package/actions/runs/2480647542
Workflow name: Generic (Bazel) tag main default SLSA2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa2.yml
Trigger: push
Branch: v21.0.1
Date: Sat Jun 11 17:01:00 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.2
Run: https://github.com/slsa-framework/example-package/actions/runs/2482125375
Workflow name: Generic (Bazel) tag main default SLSA2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa2.yml
Trigger: push
Branch: v21.0.2
Date: Sun Jun 12 03:25:24 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.3
Run: https://github.com/slsa-framework/example-package/actions/runs/2485877083
Workflow name: Generic (Bazel) tag main default SLSA2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa2.yml
Trigger: push
Branch: v21.0.3
Date: Mon Jun 13 03:39:04 UTC 2022

**Comment by mihaimaruseac** [comment]
Should be resolved by https://github.com/slsa-framework/example-package/commit/1f99d71d8117fd7760e0467f255baa240b3ddad0 but probably the automation won't detect this for the next ~8 hours (commenting to auto-subscribe to notifications here and revise if it doesn't get auto-closed)

**Comment by laurentsimon** [comment]
Feel free to start the run manually or via the CLI `bash .github/workflows/scripts/manual-run-e2e.sh e2e.generic-bazel.tag.main.default.slsa2.yml`

Note: I hit some rate limit on my PAT earlier today, so beware this may happen :/
