### ISSUE TITLE
[bug][bazel] secure-upload-folder not referenced at main

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2550]
`slsa-framework/slsa-github-generator/.github/actions/secure-upload-folder` isn't referenced at main in the internal `bazel` builder. Is the references check missing this?

https://github.com/slsa-framework/slsa-github-generator/blob/ea62fe80312d00a7185241c8791fa94736be890d/internal/builders/bazel/action.yml#L78

**Comment by laurentsimon** [comment]
Good catch. This is also true of Java builders, which are not tracked in the reference pre-submits. I'll send a PR
