### ISSUE TITLE
[bug] The specified go version file at: go.mod does not exist

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#2661]
The `go-version-file` input to the Go builder passes the value to `setup-go` but since the project is checked out to a different directory than the `GITHUB_WORKSPACE` `setup-go` will fail to find the file.

The path given to `setup-go` needs to be joined with `inputs.path` where the project is checked out in `secure-project-checkout`.

https://github.com/slsa-framework/slsa-github-generator/blob/7e31fad1e6c846162e8b794a6ca0d04417a17e0d/.github/actions/secure-project-checkout-go/action.yml#L62

**Comment by laurentsimon** [comment]
@raghavkaul is this the problem you encountered on scorecard a couple weeks back? 

Let's create e2e test for this one, if we don't have one already. I can squeeze this in the next release (this week)

**Comment by OpenWaygate** [comment]
Seems that the fixing code is not contained in `v1.9.0`

**Comment by ianlewis** [comment]
> Seems that the fixing code is not contained in `v1.9.0`

Yes, this still hasn't been released :(

**Comment by laurentsimon** [comment]
We plan to release very soon. /cc @ramonpetgrave64 We have one or two more issues to address
