### ISSUE TITLE
[bug] Maven / Gradle builders fail to run concurrently

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#2662]
If two jobs within the same workflow run the Maven builder, e.g. on two projects hosted on the same repo, the target folders will have a name collision, due to lack of randomization in https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/gradle/action.yml#L120-L123 and similarly in https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/maven/action.yml#L108-L111

The artifact name (not the name on disk) needs to be randomized, as in 
https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/nodejs/action.yml#L84-L94

This requires an update to:
1. The internal Action. It must add randomization and return a new output
2. The publish / download Actions. They need an additional input for the randomized name.
4. e2e tests

NOTE: The nodejs builder has the relevant code as example.

**Comment by laurentsimon** [comment]
Relevant part of the BYOB docs https://github.com/slsa-framework/slsa-github-generator/blob/main/BYOB.md#update-tca

**Comment by AdamKorcz** [comment]
1 and 2 are fixed here: https://github.com/slsa-framework/slsa-github-generator/pull/2665
