### ISSUE TITLE
Gradle builder not working (with or without wrapper)

### ISSUE THREAD

**Issue by bbossola** [slsa-framework/slsa-github-generator#2727]
I attempted to run the Gradle builder as a Github Action on a sample project following the instructions, but it does not work.

I attempted using a standard wrapper:
https://github.com/bbossola/gradle-sample-project/actions/runs/6240805328/job/16941718533 

And without:
https://github.com/bbossola/gradle-sample-project/actions/runs/6240908435/job/16942059861

In both situation, the project is not built and the action fails. I followed the instructions provided. Please advice.

**Comment by laurentsimon** [comment]
@AdamKorcz Can you take a look?
/cc @loosebazooka

**Comment by loosebazooka** [comment]
okay, sorry I finally got a chance to look at this.

In each case:

(1) you need to also check in the `gradle-wrapper.jar`  into your repo (see: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper)

(2) this action depends on the existence of the gradle wrapper, the runtime container does not contain gradle, so it can't run anything

**Comment by laurentsimon** [comment]
DO we need to update the documentation?

**Comment by loosebazooka** [comment]
I think (1) is a mistake by the user, I think (2) is maybe a problem with documentation. Ensure that we explicitly *require* gradle wrapper.

**Comment by laurentsimon** [comment]
Thanks @loosebazooka feel free to send a PR to improve documentation and tag me on it

**Comment by loosebazooka** [comment]
https://github.com/slsa-framework/slsa-github-generator/pull/2866

**Comment by laurentsimon** [comment]
Also merged https://github.com/slsa-framework/slsa-github-generator/pull/3083 and created https://github.com/slsa-framework/slsa-github-generator/issues/3086 to add e2e2 tests

@ramonpetgrave64

**Comment by ramonpetgrave64** [comment]
Fix pending in https://github.com/slsa-framework/slsa-github-generator/pull/3250, but we should find a way to test the new behavior, where the project directory is the same as the repository root.

**Comment by laurentsimon** [comment]
Can you try calling your fork from your own project? I think you'll need to update this line in your fork https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_maven_slsa3.yml#L84, to ensure it calls your fork instead of this repo. Let me know if this works or not.

**Comment by ianlewis** [comment]
Fixed by #3250 
e2e test added here: https://github.com/slsa-framework/example-package/pull/323
