### ISSUE TITLE
E2E: Generic schedule main default SLSA3

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#289]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2492703991
Workflow name: Generic schedule main default SLSA3
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Tue Jun 14 04:10:47 UTC 2022

**Comment by ianlewis** [comment]
Verification fails for older releases of the verifier before we changed the file name of the generic workflow.

Verifier should probably differentiate between the GAed workflows and those that aren't GAed yet.

**Comment by laurentsimon** [comment]
yes. I made some changes in the direction yesterday https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e.go.default.verify.sh#L27-L32

for verifier versions that don't support the `release` trigger. We could do something similar?

In the long-term, we could have some help function like version_lt, version_gt, version_range, major_lt, etc

**Comment by ianlewis** [comment]
No, that's pretty much it. I was just thinking of adding checks like version_gt or version_lt

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2499653756
Workflow name: .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Wed Jun 15 04:00:33 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2506587623
Workflow name: .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Thu Jun 16 03:55:25 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2513193501
Workflow name: .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Fri Jun 17 03:58:52 UTC 2022

**Comment by ianlewis** [comment]
@laurentsimon @asraa Did something change with the verifier or rekor recently? The e2e tests are now failing saying the verifier at HEAD can't find the rekor entries for the generated provenance

`FAILED: SLSA verification failed: error searching rekor entries: no matching entries found`

**Comment by laurentsimon** [comment]
Yep, there's a rekor problem that, see https://github.com/slsa-framework/slsa-github-generator/issues/327#issuecomment-1158003639

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2519115266
Workflow name: .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Sat Jun 18 03:48:12 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2522670606
Workflow name: .github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Sun Jun 19 03:58:36 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2526425615
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Mon Jun 20 03:48:08 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2539740238
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Wed Jun 22 03:56:56 UTC 2022

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2546901523
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.schedule.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Thu Jun 23 05:22:50 UTC 2022

**Tests are passing now. Closing this issue.**
