### ISSUE TITLE
E2E: Generic (Bazel) tag main default SLSA2

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#292]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.5
Run: https://github.com/slsa-framework/example-package/actions/runs/2492858819
Workflow name: Generic (Bazel) tag main default SLSA2
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.5
Date: Tue Jun 14 05:00:06 UTC 2022

**Comment by ianlewis** [comment]
Same cause as #289

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.6
Run: https://github.com/slsa-framework/example-package/actions/runs/2499601690
Workflow name: .github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.6
Date: Wed Jun 15 03:46:52 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.7
Run: https://github.com/slsa-framework/example-package/actions/runs/2513103865
Workflow name: .github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.7
Date: Fri Jun 17 03:33:48 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.8
Run: https://github.com/slsa-framework/example-package/actions/runs/2519057156
Workflow name: .github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.8
Date: Sat Jun 18 03:27:52 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.9
Run: https://github.com/slsa-framework/example-package/actions/runs/2522635953
Workflow name: .github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.9
Date: Sun Jun 19 03:45:11 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.10
Run: https://github.com/slsa-framework/example-package/actions/runs/2526336066
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.10
Date: Mon Jun 20 03:23:58 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.12
Run: https://github.com/slsa-framework/example-package/actions/runs/2539667176
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.12
Date: Wed Jun 22 03:37:43 UTC 2022

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v21.0.15
Run: https://github.com/slsa-framework/example-package/actions/runs/2547180816
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.tag.main.default.slsa3.yml
Trigger: push
Branch: v21.0.15
Date: Thu Jun 23 06:33:45 UTC 2022

**Tests are passing now. Closing this issue.**
