### ISSUE TITLE
[bug] SPECIFICATIONS google doc is private

### ISSUE THREAD

**Issue by noqcks** [slsa-framework/slsa-github-generator#2926]
**Describe the bug**

The google doc referenced for source level provenance on the SPECIFICATIONS page is private. 

https://github.com/slsa-framework/slsa-github-generator/blob/main/SPECIFICATIONS.md#source-level-provenance

https://docs.google.com/document/d/10B-8R3NIGvcPuoIhqb-p18oOe78m6SiiukfE7NyvnYQ/preview

**Expected behavior**

Access to this document

**Comment by ianlewis** [comment]
@TomHennen This doc doesn't seem to be accessible publicly though you have marked it for public consumption. Could you take a look at the current access restrictions?

@laurentsimon Is it worth making a copy for this repo? Currently we don't support any kind of source attestations though so I'm not sure keeping this section in the SPECIFICATIONS doc is really worth it until we do.

**Comment by TomHennen** [comment]
> @TomHennen This doc doesn't seem to be accessible publicly though you have marked it for public consumption. Could you take a look at the current access restrictions?

Hmm, it looks like I cannot share a doc from my work Google Docs completely publicly.  It has previously been shared with https://groups.google.com/g/slsa-discussion/ (which anyone can join).  When the doc was originally shared I think the instructions to join that group were noted with it, but they've gotten lost.

We can either 1) add the instructions back, or 2) I can make a copy with my personal Google Docs account and share that publicly. 3) Turn it into markdown and upload somewhere (where?).

Any thoughts?

**Comment by laurentsimon** [comment]
> @laurentsimon Is it worth making a copy for this repo? Currently we don't support any kind of source attestations though so I'm not sure keeping this section in the SPECIFICATIONS doc is really worth it until we do.

Let's just remove the link and point folks to the tracking issue https://github.com/slsa-framework/slsa/issues/956 if they want to know more. I'll send a PR
