### ISSUE TITLE
E2E: Generic tag main default SLSA3

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#293]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.8
Run: https://github.com/slsa-framework/example-package/actions/runs/2492868461
Workflow name: Generic tag main default SLSA3
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.8
Date: Tue Jun 14 05:03:48 UTC 2022

**Comment by ianlewis** [comment]
Same cause as #289

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.9
Run: https://github.com/slsa-framework/example-package/actions/runs/2499619203
Workflow name: .github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.9
Date: Wed Jun 15 03:51:42 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.10
Run: https://github.com/slsa-framework/example-package/actions/runs/2506535079
Workflow name: .github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.10
Date: Thu Jun 16 03:40:35 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.11
Run: https://github.com/slsa-framework/example-package/actions/runs/2513141269
Workflow name: .github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.11
Date: Fri Jun 17 03:39:32 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.12
Run: https://github.com/slsa-framework/example-package/actions/runs/2519068586
Workflow name: .github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.12
Date: Sat Jun 18 03:31:16 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.13
Run: https://github.com/slsa-framework/example-package/actions/runs/2522646802
Workflow name: .github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.13
Date: Sun Jun 19 03:49:32 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.14
Run: https://github.com/slsa-framework/example-package/actions/runs/2526350125
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.14
Date: Mon Jun 20 03:28:45 UTC 2022

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v18.0.18
Run: https://github.com/slsa-framework/example-package/actions/runs/2547309320
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.main.default.slsa3.yml
Trigger: push
Branch: v18.0.18
Date: Thu Jun 23 07:02:01 UTC 2022

**Tests are passing now. Closing this issue.**
