### ISSUE TITLE
[feature] e2e tests for new `provenance-registry` option

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#2981]
Once https://github.com/slsa-framework/slsa-github-generator/issues/2956 is merged, let's add an e2e tests in the https://github.com/slsa-framework/example-package/tree/main/.github/workflows

Need to figure out which registry / account we use for the second registry.

/cc @saisatishkarra

**Comment by saisatishkarra** [comment]
@laurentsimon The #2962 is merged. I can work on the e2e test workflow. Is there a consensus on the second registry?

**Comment by laurentsimon** [comment]
Let's try to use docker (our existing tests use GitHub registry, I think). I'll find a way to create an account for testing. Let me know if you're able to make sense of the e2e tests. We only need to add one test, you can use https://github.com/slsa-framework/example-package/blob/bf2a15594ee748d53bdea8e6b5471c77fe6135dd/.github/workflows/e2e.container.schedule.main.default.slsa3.yml#L86 as a starting point and update the names / options. 

Verification starts in https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e.container.default.verify.sh. As a first step, it's probably enough to export the `COSIGN_X` if the value is set in the config file (you can detect that by using a proper name for the workflow, see some examples for Go https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e.go.default.verify.sh#L44-L46).

Let me know if that makes sense or not.

Thanks again for the help, much appreciated!

**Comment by saisatishkarra** [comment]
@laurentsimon I looked at the tests and they make sense. I would start with `e2e.container.schedule.main.provenance-registry.slsa3.yml` and reuse most of the GHCR registry for pushing the image and add the new docker registry to push provenance to a separate registry. 

Would you mind sharing the secrets / env values for the new docker repository for hosting provenance?

**Comment by laurentsimon** [comment]
I'l add the secrets into the settings. Will let you know this week when done.

**Comment by laurentsimon** [comment]
I've created a secret named `E2E_DOCKER_HUB_TOKEN`, username laurentsimon. Let's use this account for the container images, and the gcr.io for the provenance. Let's also delete the container when it's used. 
Please cc me on the PR you send. Thank you!

**Comment by laurentsimon** [comment]
Correct: if possible we can swap them., unless it complicates things too much. My reasoning was that I'd like to delete the images after each run to avoid docker's complaining. I'm not sure how to delete the attestations only... but it's that possible let's do that instead. Maybe cosign has a command to delete all attestations for a given image?

**Comment by saisatishkarra** [comment]
@laurentsimon Here is the PR: https://github.com/slsa-framework/example-package/pull/294. LMK if anything needs changing. Can you confirm if you expect to delete the container image (workflow name) in the docker hub vs. the provenance package in GHCR vs. both?

**Comment by laurentsimon** [comment]
deleting the image from docker should be enough. The token should have the right permissions. Thanks

**Comment by saisatishkarra** [comment]
@laurentsimon After some digging seems like docker is deprecating the Advanced Image management API  and hub-tool (experimental) doesn't yet support providing password from env / doesn't obey docker login creds, and is pending.

Here are the 3 issues for deleting from dockerhub: 
- https://github.com/docker/roadmap/issues/534
- https://docs.docker.com/docker-hub/api/latest/#tag/images/operation/PostNamespacesDeleteImages
 - https://github.com/docker/hub-tool/pull/198
 
2 Solution alternatives:

- **Option 1:** Push container image to GHCR and provenance image to dockerhub (i.e. Swap token permissions and registries for storing image and provenance). Leverage https://github.com/marketplace/actions/delete-ghcr-io-package-tag to delete docker container image from GHCR and leave out provenance in a docker registry

- **Option 2:** Push container image to dockerhub and provenance to GHCR. Skip deletion/pruning of images and document reasons.

Clarifications needed:
- LMK what option to proceed with?
- If **Option 1** is chosen, confirm that the `GH_TOKEN (E2E_CONTAINER_TOKEN)` has permission to delete the image from GHCR / and What repository to push the provenance in docker hub (Currently Using workflow name as docker repo).

**Comment by saisatishkarra** [comment]
PR https://github.com/slsa-framework/example-package/pull/294# merged for e2e

**Comment by saisatishkarra** [comment]
@ianlewis  / @laurentsimon let me know if this feature is ready (i.e. the e2e test is working???) to be used and when the tag/release is made?

 Also is there something that needs to be worked on on the verifier end?

**Comment by ianlewis** [comment]
Looks like it failed for some reason. I'll take a look on Monday.
https://github.com/slsa-framework/slsa-github-generator/issues/3024

**Comment by laurentsimon** [comment]
It's working now.
