### ISSUE TITLE
Verifying hashes passed between jobs

### ISSUE THREAD

**Issue by behnazh-w** [slsa-framework/slsa-github-generator#302]
Currently the hashes of the artifacts passed between jobs are [validated](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml#L256-L258) using:
```
sha256sum --strict --check --status
```
Looks like the workflow misses actually comparing the [computed hash](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml#L253) with the [hash passed as input](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml#L248)?

**Comment by laurentsimon** [comment]
Thanks for looking into the code.

The computed hash is only calculated to be printed in the log.

The command `echo "$BUILDER_HASH $BUILDER_BINARY" | sha256sum --strict --check --status || exit -2` does tell sha256sum to verify `$BUILDER_BINARY` against `$BUILDER_HASH`. sha256sum looks up `$BUILDER_BINARY` on disk, computes the sha256, then compares it to `$BUILDER_HASH $BUILDER_BINARY`, which is the expected entry of files like https://github.com/slsa-framework/slsa-verifier/blob/main/SHA256SUM.md. Each line is `<hash> <binary-name>`

We have e2e tests to verify that, see:
https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.go.schedule.main.adversarial-binary-upload.slsa3.yml
https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.go.schedule.main.adversarial-build-provenance.slsa3.yml
https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.go.schedule.main.adversarial-build.slsa3.yml

Note that we plan to move this code to an Action to make it re-usable. As you point out, bash/sha256sum is not the easiest to read.

Feel free to test and tell us if you find a problem, though. We'd love to hear it whether you find a bug or not.

**Comment by ianlewis** [comment]
Repo: https://github.com/ianlewis/example-package/tree/main
Run: https://github.com/ianlewis/example-package/actions/runs/2499220503
Workflow name: go schedule main SLSA3 adversarial build
Workflow file: https://github.com/ianlewis/example-package/tree/main/.github/workflows/e2e.go.schedule.main.adversarial-build.slsa3.yml
Trigger: schedule
Branch: main
Date: Wed Jun 15 01:38:19 UTC 2022

**Tests are passing now. Closing this issue.**

**Comment by laurentsimon** [comment]
(note: our e2e tests are trying to close this issue automatically because it contains the path to the workflows, and we use the path as to identify opened e2e issues - we need to be smarter and look at the title if we can, maybe).

**Comment by behnazh-w** [comment]
Thanks for the clarification. I was puzzled by `COMPUTED_HASH` variable. All good!

> sha256sum looks up $BUILDER_BINARY on disk,

I'm wondering if the attacker can take advantage of this. Would reading from disk circumvent the guarantees of using [job output](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) as a trusted channel? :thinking: 

> Note that we plan to move this code to an Action to make it re-usable. As you point out, bash/sha256sum is not the easiest to read.

That would be great because it's been used in various places in the workflow :slightly_smiling_face:

**Comment by ianlewis** [comment]
> I'm wondering if the attacker can take advantage of this. Would reading from disk circumvent the guarantees of using [job output](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) as a trusted channel? 🤔

Hi! The reason we check the sha here is because we are explicitly not trusting the binary on the disk and comparing it against a sha we got from a trusted job output in order to verify it. My understanding is that we aren't reading the sha from an untrusted source so we should be ok here.

The binary is not trusted until the sha has been verified because it is transferred between jobs by uploading it as an artifact and then downloading it later and thus it could have been modified by the user's workflow in the meantime.

**Comment by behnazh-w** [comment]
Thanks for answering my questions. I'll close the issue.

**Comment by ianlewis** [comment]
> Thanks for answering my questions. I'll close the issue.

No worries! Thanks for taking a look at the code and keeping us honest!

**Comment by laurentsimon** [comment]
+1 on what @ianlewis said, thanks for looking at the code!
