### ISSUE TITLE
E2E: generic tag branch1 default slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#305]
Repo: https://github.com/slsa-framework/example-package/tree/v22.0.1
Run: https://github.com/slsa-framework/example-package/actions/runs/2499606173
Workflow name: .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Trigger: push
Branch: v22.0.1
Date: Wed Jun 15 03:48:02 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v22.0.3
Run: https://github.com/slsa-framework/example-package/actions/runs/2519058843
Workflow name: .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Trigger: push
Branch: v22.0.3
Date: Sat Jun 18 03:27:21 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v22.0.4
Run: https://github.com/slsa-framework/example-package/actions/runs/2522639044
Workflow name: .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Trigger: push
Branch: v22.0.4
Date: Sun Jun 19 03:46:06 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v22.0.5
Run: https://github.com/slsa-framework/example-package/actions/runs/2526335702
Workflow name: .github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Trigger: push
Branch: v22.0.5
Date: Mon Jun 20 03:23:06 UTC 2022

**Comment by ianlewis** [comment]
Hmm, this seems to be running e2e tests based on a trigger from a go workflow.

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v22.0.10
Run: https://github.com/slsa-framework/example-package/actions/runs/2547260921
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.tag.branch1.default.slsa3.yml
Trigger: push
Branch: v22.0.10
Date: Thu Jun 23 06:53:45 UTC 2022

**Tests are passing now. Closing this issue.**
