### ISSUE TITLE
[bug] Document that v3 of actions/download-artifact must be used to download provenance

### ISSUE THREAD

**Issue by jkreileder** [slsa-framework/slsa-github-generator#3066]
If one wants to download the provenance artifact, `actions/download-artifact@v3` has to be used because the workflows use `actions/upload-artifact@v3` to upload and `actions/download-artifact@v4` is [not backwards compatible](https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes).

IMHO, this should be documented.

**Comment by ianlewis** [comment]
Am I right in understanding that upload/download-artifact v3 and v4 are mutually incompatible? i.e. you can't download an artifact with `download-artifact@v4` when uploaded with `upload-artifact@v3` and you *also* cannot download an artifact with `download-artifact@v3` that was uploaded with `upload-artifact@v4` ?

**Comment by rgacogne** [comment]
> Am I right in understanding that upload/download-artifact v3 and v4 are mutually incompatible? i.e. you can't download an artifact with `download-artifact@v4` when uploaded with `upload-artifact@v3` and you **also** cannot download an artifact with `download-artifact@v3` that was uploaded with `upload-artifact@v4` ?

Correct.
