### ISSUE TITLE
[feature] Use upload-artifact v4

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#3068]
we may need a compatibility option as argument to avoid breaking folks who currently use v3

**Comment by jkreileder** [comment]
upload-artifact@v4+ also is not yet available for GHES, so v3 should definitely be kept as the default version.

**Comment by behnazh-w** [comment]
I think it makes more sense to release a new version of the generator that is compatible with v4 by default (as soon as possible to avoid breaking pipelines that have already updated `download-artifact` to v4) and add a backward compatibility argument for v3. 

The changelog and documentation should warn about the compatibility issue and that users should use `download-artifact@v4` by default.

**Comment by ianlewis** [comment]
Am I right in understanding that upload/download-artifact v3 and v4 are mutually incompatible? i.e. you can't download an artifact with download-artifact@v4 when uploaded with upload-artifact@v3 and you also cannot download an artifact with download-artifact@v3 that was uploaded with upload-artifact@v4 ?

**Comment by behnazh-w** [comment]
> Am I right in understanding that upload/download-artifact `v3` and `v4` are mutually incompatible? i.e. you can't download an artifact with `download-artifact@v4` when uploaded with `upload-artifact@v3` and you **also** cannot download an artifact with `download-artifact@v3` that was uploaded with `upload-artifact@v4` ?

Yes, you're right. See https://github.com/actions/download-artifact/issues/250#issuecomment-1857340787.

**Comment by ianlewis** [comment]
> Yes, you're right. See [actions/download-artifact#250 (comment)](https://github.com/actions/download-artifact/issues/250#issuecomment-1857340787).

Got it. Thanks.

> I think it makes more sense to release a new version of the generator that is compatible with v4 by default (as soon as possible to avoid breaking pipelines that have already updated `download-artifact` to v4) and add a backward compatibility argument for v3.
> 
> I would argue that this release would have a breaking change. So the release version should be `slsa-github-generator@v2.0.0`.

I agree about the compatibility and version number but is an option really necessary? In what situation do you think users would need to use it? I expect that it's not a huge deal to upgrade to `download-artifact@v4` and that it's ok for us to ask them to upgrade it on a major version change of the generators but are there other blockers for users that we should know about?

**Comment by behnazh-w** [comment]
As @jkreileder pointed out `download-artifact@v4` is not compatible with [GitHub Enterprise Server](https://github.com/actions/upload-artifact#v4---whats-new). So, if the you don't add the option for v3 compatibility, you might need to have a separate release of  slsa-github-generator artifacts for GHES, which is too much work probably.

**Comment by ianlewis** [comment]
> As @jkreileder pointed out `download-artifact@v4` is not compatible with [GitHub Enterprise Server](https://github.com/actions/upload-artifact#v4---whats-new). So, if the you don't add the option for v3 compatibility, you might need to have a separate release of slsa-github-generator artifacts for GHES, which is too much work probably.

I'm not sure how hosted runners work on GHES. Are hosted runners supported or do users need to use self-hosted runners?

**Comment by behnazh-w** [comment]
> I'm not sure how hosted runners work on GHES. Are hosted runners supported or do users need to use self-hosted runners?

Yes, GitHub Enterprise [supports](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#larger-runners) standard GitHub-hosted runners.

**Comment by ianlewis** [comment]
I think that's Github Enterprise Cloud which supports hosted runners (as it's hosted by Github) vs Github Enterprise Server which doesn't support hosted runners (as it's self-hosted).

**Comment by jkreileder** [comment]
@ianlewis you're right, GHES only supports self-hosted runners.

**Comment by kapilt** [comment]
This is currently labeled feature, but I think its closer to a bug, in that its breakage for new users trying to use the generator workflow, as happened to me yesterday, or extant users dealing with an update to artifact actions. also fwiw having also done the dependabot driven update from v3 to v4 on artifact actions, it does have some nuance/work for projects potentially based on usage wrt to immutable cache names.

**Comment by jkreileder** [comment]
@behnazh-w I'm not sure if maintaining two versions would be too much work: The only difference between slsa-github-generator@v1 and slsa-github-generator@v2 would be the dependency on the up/download-artifact version - 10 lines of yaml code if I counted correctly.
Merging backing other changes from slsa-github-generator@v2 to slsa-github-generator@v1 should be easy.

For users that would mean:
- GHES users stay at slsa-github-generator@v1 just like they must stay at up/download-artifact@v3
- All others can upgrade to slsa-github-generator@v2

**Comment by behnazh-w** [comment]
> @ianlewis you're right, GHES only supports self-hosted runners.

>For users that would mean:
>
>   GHES users stay at slsa-github-generator@v1 just like they must stay at up/download-artifact@v3
>   All others can upgrade to slsa-github-generator@v2


@jkreileder I was wrongly thinking of the Github Enterprise Cloud when I proposed to have backward compatibility with GHES earlier.  I don't think slsa-github-generator supports self-hosted runners needed by GHES anyway. So, we might not need backward-compatibility altogether?
 
@laurentsimon @ianlewis please correct me if I'm wrong.

**Comment by ianlewis** [comment]
> @jkreileder I was wrongly thinking of the Github Enterprise Cloud when I proposed to have backward compatibility with GHES earlier. I don't think slsa-github-generator supports self-hosted runners needed by GHES anyway. So, we might not need backward-compatibility altogether?
> 
> @laurentsimon @ianlewis please correct me if I'm wrong.

Yes. That was my thinking.

**Comment by ianlewis** [comment]
This also seems to be an issue regarding the [deprecation of Node 16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). The v3 versions of `upload-artifact` use Node 16 and haven't been updated to Node 20.

```
[build / slsa-run / verify-token](https://github.com/slsa-framework/example-package/actions/runs/8042728772/job/21963776341)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by laurentsimon** [comment]
We're working on this for next release. Given the comments above, we're going to do a major release that will only support v4 upload / download Action.
