### ISSUE TITLE
E2E: generic workflow_dispatch branch1 default slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#307]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2499649591
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Wed Jun 15 04:00:18 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2506579715
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Thu Jun 16 03:53:33 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2513186282
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Fri Jun 17 03:53:15 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2519110060
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Sat Jun 18 03:47:26 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2522667899
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Sun Jun 19 03:57:24 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2532900551
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Tue Jun 21 03:59:24 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2539734252
Workflow name: .github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Wed Jun 22 03:55:28 UTC 2022

**Comment by ianlewis** [comment]
Should be fixed by https://github.com/slsa-framework/example-package/pull/63

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2546903079
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Thu Jun 23 05:24:06 UTC 2022

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2547223249
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.workflow_dispatch.branch1.default.slsa3.yml
Trigger: workflow_dispatch
Branch: branch1
Date: Thu Jun 23 06:42:12 UTC 2022

**Tests are passing now. Closing this issue.**
