### ISSUE TITLE
[feature] `attestation-name` deprecation warning

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#3072]
We should emit a warning if users are using the deprecated `attestation-name` input.

Related #3031

**Comment by kpk47** [comment]
It looks like you added such a warning in #777. 
```
            if [ "$UNTRUSTED_DEPRECATED_ATTESTATION_NAME" != "" ]; then
              echo "WARNING: deprecated attestation-name was used. Use provenance-name instead."
              untrusted_prov_name="$UNTRUSTED_DEPRECATED_ATTESTATION_NAME"
            fi
   ```

**Comment by ianlewis** [comment]
I suppose it should be a output as as a [warning](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message) workflow command so that it's surfaced in the Actions run UI.
