### ISSUE TITLE
E2E: generic push branch1 default slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#308]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2499661361
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Wed Jun 15 04:03:11 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2506593864
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Thu Jun 16 03:57:44 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2513202270
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Fri Jun 17 03:57:38 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2519120608
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Sat Jun 18 03:51:01 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2522674976
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Sun Jun 19 04:00:23 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2532913906
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Tue Jun 21 04:03:06 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2539749077
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Wed Jun 22 04:00:05 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2546901861
Workflow name: .github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Thu Jun 23 05:19:28 UTC 2022

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/branch1
Run: https://github.com/slsa-framework/example-package/actions/runs/2546949683
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic.push.branch1.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic.push.branch1.default.slsa3.yml
Trigger: push
Branch: branch1
Date: Thu Jun 23 05:36:28 UTC 2022

**Tests are passing now. Closing this issue.**
