### ISSUE TITLE
[feature] e2e tests for #3083

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#3086]
Need to close the loop and add e2e2 tests for https://github.com/slsa-framework/slsa-github-generator/pull/3083

**Comment by pandaninjas** [comment]
My PR might not work just yet: see https://github.com/thefightagainstmalware/NoSession/actions/runs/7545330082/job/20540724782.
This issue might not just be moving the same file from source to destination, it might also be moving a parent directory into a child (or vice versa)

**Comment by laurentsimon** [comment]
I'll see if the e2e2 tests fail. If they do, I'll revert :)

**Comment by pandaninjas** [comment]
> I'll see if the e2e tests fail. If they do, I'll revert :)

The e2e test probably won't fail, but the PR doesn't do what it set out to accomplish.

**Comment by laurentsimon** [comment]
ah you're right! Let me revert now then

**Comment by laurentsimon** [comment]
I think this is fixed. Closing
