### ISSUE TITLE
E2E: generic-bazel workflow_dispatch main default slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#309]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2499661702
Workflow name: .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Wed Jun 15 04:03:16 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2506595014
Workflow name: .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Thu Jun 16 03:58:58 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2513203615
Workflow name: .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Fri Jun 17 03:58:18 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2519121430
Workflow name: .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Sat Jun 18 03:51:53 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2522675366
Workflow name: .github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Sun Jun 19 04:02:38 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2532914708
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Tue Jun 21 04:04:33 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2539749645
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Wed Jun 22 04:01:33 UTC 2022

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2546899991
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.workflow_dispatch.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Thu Jun 23 05:24:58 UTC 2022

**Tests are passing now. Closing this issue.**
