### ISSUE TITLE
E2E: generic-bazel push main default slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#310]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2499660281
Workflow name: .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Wed Jun 15 04:03:45 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2506593857
Workflow name: .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Thu Jun 16 03:58:27 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2513201786
Workflow name: .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Fri Jun 17 03:57:58 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2519120524
Workflow name: .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Sat Jun 18 03:51:14 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2522674483
Workflow name: .github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Sun Jun 19 04:00:54 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2532913257
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Tue Jun 21 04:03:25 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2539748648
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Wed Jun 22 04:00:11 UTC 2022

**Comment by ianlewis** [comment]
Should be fixed by https://github.com/slsa-framework/example-package/pull/63

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2546837004
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.push.main.default.slsa3.yml
Trigger: push
Branch: main
Date: Thu Jun 23 05:08:08 UTC 2022

**Tests are passing now. Closing this issue.**
