### ISSUE TITLE
E2E: generic-bazel schedule main default slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#311]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2499669483
Workflow name: .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Wed Jun 15 04:05:58 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2506601116
Workflow name: .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Thu Jun 16 04:01:00 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2513211721
Workflow name: .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Fri Jun 17 04:01:30 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2519127901
Workflow name: .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Sat Jun 18 03:54:21 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2522681416
Workflow name: .github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Sun Jun 19 04:04:30 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2526445909
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Mon Jun 20 03:55:15 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2532922223
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Tue Jun 21 04:06:14 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2539759969
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: schedule
Branch: main
Date: Wed Jun 22 04:03:29 UTC 2022

**Comment by ianlewis** [comment]
Should be fixed by https://github.com/slsa-framework/example-package/pull/63

**Comment by ianlewis** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/main
Run: https://github.com/slsa-framework/example-package/actions/runs/2546871949
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.generic-bazel.schedule.main.default.slsa3.yml
Trigger: workflow_dispatch
Branch: main
Date: Thu Jun 23 05:17:01 UTC 2022

**Tests are passing now. Closing this issue.**
