### ISSUE TITLE
Feature: log rekor UUID to log

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#318]
To help with troubleshooting rekor, let's log the rekor UUID after upload.

I'm wondering if it would help to embed the UUID as part of this proposal https://github.com/sigstore/cosign/issues/1743

/cc @asraa

**Comment by laurentsimon** [comment]
I don't know the inner details of rekor: is the UUID backed by Trillian or Redis? I was assuming UUID was backed by Trillian: so having the UUID in the envelope would allow the rekor lookup even if Redis has problems, in order to verify that the entry is in the log.

**Comment by asraa** [comment]
This is done as well
