### ISSUE TITLE
Upgrade upload/download-artifact in sync across all org

### ISSUE THREAD

**Issue by mihaimaruseac** [slsa-framework/slsa-github-generator#3239]
Because `upload-artifact` and `download-artifact` are not compatible across v3-v4 major bump, we need to upgrade them across all repos at the same time, instead of when Renovate opens a PR in one repo.

Probably also need to cut new releases for that.

**Comment by mihaimaruseac** [comment]
Opened https://github.com/slsa-framework/example-package/issues/320 to also make sure the test repo is in the known.

**Comment by mihaimaruseac** [comment]
It seems this is also affecting OSS project that have updated the actions (via Dependabot, etc.) so now are using `upload-artifact@v4` in the release workflow. This is a ticking timebomb in all OSS projects :(

**Comment by behnazh-w** [comment]
@mihaimaruseac We discussed this problem a month ago, which is still open: https://github.com/slsa-framework/slsa-github-generator/issues/3068

Indeed many releases have failed after upgrading `download-artifact` to v4.

**Comment by mihaimaruseac** [comment]
Thank you. Closing this in favor of that one.
