### ISSUE TITLE
Examples on using generic provenance for Java applications

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#331]

**Comment by ianlewis** [comment]
Maven seems like it can store arbitrary files in it's releases. A future Java-specific ecosystem builder could do this automatically itself, but for the generic generator we can create examples that use the deploy plugin to deploy the provenance file.
https://maven.apache.org/plugins/maven-deploy-plugin/usage.html

**Comment by ianlewis** [comment]
@laurentsimon We now have some [docs for Java](https://github.com/slsa-framework/slsa-github-generator/blob/1d7962b4eae7a525f14cd5b17cd7467c7f311fea/internal/builders/generic/README.md#provenance-for-java) but I wonder if we shouldn't include docs for verification as well.

Not for GA of the generic workflow, but someday it might be nice to have a maven plugin for sigstore much like the [gpg plugin](https://maven.apache.org/plugins/maven-gpg-plugin/). That would make it easy to publish and consume Java artifacts via maven.

**Comment by laurentsimon** [comment]
Completely agree on Maven plugin. Should be easy to do given the Sigstore example https://github.com/sigstore/sigstore-maven-plugin

I've created https://github.com/slsa-framework/slsa-verifier/issues/155 for tracking.

/cc @loosebazooka

**Comment by laurentsimon** [comment]
> We now have some [docs for Java](https://github.com/slsa-framework/slsa-github-generator/blob/1d7962b4eae7a525f14cd5b17cd7467c7f311fea/internal/builders/generic/README.md#provenance-for-java) but I wonder if we shouldn't include docs for verification as well.

Good point. I think until now we just told people to use the verifier. Shall we an an explicit command in the README or link to the verifier repo instead? Wdut?

**Comment by ianlewis** [comment]
> > We now have some [docs for Java](https://github.com/slsa-framework/slsa-github-generator/blob/1d7962b4eae7a525f14cd5b17cd7467c7f311fea/internal/builders/generic/README.md#provenance-for-java) but I wonder if we shouldn't include docs for verification as well.
> 
> Good point. I think until now we just told people to use the verifier. Shall we add a verifier command in the README or link to the verifier repo instead (people will need to install the verifier first, so we risk duplicating content)?
> 
> We could also create verification documentation on the verifier repository for each of the examples in the generator repository, and provide a link to cross reference doc. This way verification doc is not duplicated across repos.
> 
> Wdut?

I think we can do both, include examples of how to use the verifier, and link to the docs for more.

**Comment by laurentsimon** [comment]
SGTM. My only worry is around maintenance: having all in one place requires a single update instead of updates across repos. if you think it's do-able without too much maintain let's try - it should not change very often anyway

**Comment by ianlewis** [comment]
What we have is good enough for now. I'll think about adding some validation and we can think of more ways to make the workflows easier to adopt for Java projects as part of #594
