### ISSUE TITLE
[bug] SLSA generator blocking build pipelnes and unable to leverage sigstore due to cosign v2.2.2.1

### ISSUE THREAD

**Issue by saisatishkarra** [slsa-framework/slsa-github-generator#3392]
**Describe the bug**
@ianlewis / @haydentherapper  I see that the cosign version is bumped to v2.2.3 in the master branch. Can this SLSA generator be referenced using a SHA? Is there a plan to make an immediate release tag to unblock downstream pipelines.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by haydentherapper** [comment]
Dup of https://github.com/slsa-framework/slsa-github-generator/issues/3350

**Comment by laurentsimon** [comment]
This is fixed.
