### ISSUE TITLE
tracking reverting breaking changes before new emergency release

### ISSUE THREAD

**Issue by ramonpetgrave64** [slsa-framework/slsa-github-generator#3393]
tracking revert PRs before the next emergency release

**Comment by ramonpetgrave64** [comment]
getting some errors when trying to revert some PRs 
<img width="1118" alt="image" src="https://github.com/slsa-framework/slsa-github-generator/assets/32398091/d9e10f2d-6127-485e-8d9b-d39920f0fa4d">

**Comment by kpk47** [comment]
Can we just create a new release branch from the last release date and apply the sigstore fix to that? We won't have the chore releases since then, but we'll at least have the sigstore fix.

**Comment by ramonpetgrave64** [comment]
@kpk sounds good, we can bramch from 
https://github.com/slsa-framework/slsa-github-generator/commit/07e64b653f10a80b6510f4568f685f8b7b9ea830
and then apply the fixes from
https://github.com/slsa-framework/slsa-github-generator/pull/3355

But I think there may be an adversarial test for releasing from a non-main branch.

**Comment by laurentsimon** [comment]
If we revert:

https://github.com/slsa-framework/slsa-github-generator/pull/3313 (I'll send a PR)
Need to update the CHANGELOG for Hayden's PR
example-package revert the v3->v4 action

I'm more confident doing this in the main branch than in a different branch. The e2e tests don't work on different branch. There's just one PR left to revert https://github.com/slsa-framework/slsa-github-generator/pull/3313

**Comment by kpk47** [comment]
Okay, sounds good. Let's go with your plan.

I've got a release branch together already, so we've got that in case we need it for some reason.
