### ISSUE TITLE
release: cut a new release of the builders to include fix

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#348]
https://github.com/slsa-framework/slsa-github-generator/pull/330

**Comment by laurentsimon** [comment]
Fyi, the v1.1.0 was a pre-release, and its provenance is not verifiable so it's un-usable (the builder binary fetch fails due to provenance verification failure), so we can delete the v1.1.0.

Wdut?

**Comment by asraa** [comment]
That works!

**Comment by laurentsimon** [comment]
That should work
