### ISSUE TITLE
Show example of customing the attestation output

### ISSUE THREAD

**Issue by chipzoller** [slsa-framework/slsa-github-generator#353]
It'd be nice in the README [here](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#getting-started) if you could show an example of how to use the workflow output `attestation-name` to customize the name of the uploaded attestation. The input is shown (because it's required), but the output isn't and the default output file appears to be `attestation.intoto.jsonl`.

**Comment by ianlewis** [comment]
Just to clarify, where would you like to customize it? on the workflow run or on the release?

There is an example where it's used in the release step of the second example but I'd like to understand the use case you're thinking of.

**Comment by chipzoller** [comment]
In the workflow itself.

**Comment by ianlewis** [comment]
Right now there isn't an input that would allow you to change the name. I suppose we could add one but I think we want to keep inputs to a minimum if we can. The workflow itself is temporary so feels a bit arbitrary to me, but I can definitely see the need for customization on the release. Do you have an example somewhere we could look at?

**Comment by ianlewis** [comment]
We added an input to customize the attestation file name a while back and I created a PR to document it in #618. I think that should allow us to close this issue.

wdut? @chipzoller

**Comment by chipzoller** [comment]
Yes, that looks good, and thank you.
