### ISSUE TITLE
Is it possible to rebuild attestation previously generated for a release?

### ISSUE THREAD

**Issue by heitorlessa** [slsa-framework/slsa-github-generator#3564]
Hi everyone, we accidentally deleted the attestation file from our latest release and I'd love to hear if there's a way to reconstruct the `intoto` file.

I suspect it'd be possible to build the same release release artifact from that known commit, run `slsa`, and manually upload the `intoto` file - _not apples to apples (after the fact, some steps would be skipped)_.

For reference, this is the `intoto` file from a previous release: https://github.com/aws-powertools/powertools-lambda-python/releases/download/v2.35.1/multiple.intoto.jsonl

_Edit: links to recent release workflow._

Thank you!

---

* Release workflow that generated the attestation file: https://github.com/aws-powertools/powertools-lambda-python/actions/runs/8454033135

**Comment by laurentsimon** [comment]
Have you tried clicking the re-run button on the run workflow?

**Comment by heitorlessa** [comment]
thanks @laurentsimon. We'll change our workflow to allow for a partial re-run for these circumstances. I thought there was an undocumented way to reconstruct/pull from Rekor.
