### ISSUE TITLE
chore: v.2.0.0 - tracking

### ISSUE THREAD

**Issue by ramonpetgrave64** [slsa-framework/slsa-github-generator#3576]
Tracking PRs for the v2.0.0 release

- https://github.com/slsa-framework/slsa-github-generator/blob/02fc78b979e15ee621875039cb550e5b454b0955/RELEASE.md?plain=1#L1

**Comment by ramonpetgrave64** [comment]
Finished the initial adversarial tests. We're now doing the 2-day code freeze.
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#code-freeze

**Comment by ramonpetgrave64** [comment]
Existing tests are still passing, except for some old recurring failures

- https://github.com/slsa-framework/slsa-github-generator/issues/3581
- https://github.com/slsa-framework/slsa-github-generator/issues/3344
- https://github.com/slsa-framework/slsa-github-generator/issues/3002

**Comment by ramonpetgrave64** [comment]
Step 

https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#verify-final-version-references

```
➜  slsa-github-generator git:(main) git tag $BUILDER_TAG -f
git push upstream $BUILDER_TAG -f
error: src refspec v2.0.0 matches more than one
```

Can't push a new tag, so the steps might need re-ordering

Since this step is meant to trigger the release worrkflow, I manually invoke it instead. 
https://github.com/slsa-framework/slsa-github-generator/actions/runs/8790065191

**Comment by laurentsimon** [comment]
This is done, thanks @ramonpetgrave64 . Closing.
