### ISSUE TITLE
[feature] Refactor Hall of Fame badges so that future additions and changes are easier to manage

### ISSUE THREAD

**Issue by cpswan** [slsa-framework/slsa-github-generator#3617]
**Is your feature request related to a problem? Please describe.**

The Hall of Fame line in README.md is presently 3737 characters long. Any changes to it generate a diff to that entire line, which isn't easy to review.

**Describe the solution you'd like**

Split the badges out so each has their own line. This will make no difference to how they get rendered.
 
**Describe alternatives you've considered**

Might also consider ordering alphabetically, though at the moment it seems they're (roughly) ordered by stars (though that can change rapidly for newly popular repos).

**Additional context**

I'm happy to do a PR for this.

**Comment by ramonpetgrave64** [comment]
Yes, we would welcome a PR.

**Comment by ianlewis** [comment]
@cpswan I think you put each entry on its own line in #3616. I'll go ahead and close this but let us know if you really think we should reorder them.
