### ISSUE TITLE
[feature] Update actions/setup-go and google-github-actions/auth to avoid Node.js 16 deprecation warnings

### ISSUE THREAD

**Issue by chipzoller** [slsa-framework/slsa-github-generator#3623]
**Is your feature request related to a problem? Please describe.**
As of v2.0.0 of the generator, these two actions as called by the container generator use Node.js 16 which is deprecated and upon every run show warnings.

**Describe the solution you'd like**
Update these actions to later versions which use Node.js 20.

**Describe alternatives you've considered**
Ignore the warnings.

**Additional context**
Lots of open issues in this repository, some look like they already cover these deprecation warnings. Feel free to close if this is a duplicate and these are already being tracked.

**Comment by ianlewis** [comment]
We did upgrade our own actions in #3245 but it seems these were missed.

**Comment by ianlewis** [comment]
#3619 should also fix `softprops/action-gh-release` but we still need to update `google-github-actions/auth` since it still uses `node16`.

https://github.com/google-github-actions/auth/blob/35b0e87d162680511bf346c299f71c9c5c379033/action.yml#L189

**Comment by ianlewis** [comment]
Now that renovate is working again, this should get fixed by #3648

**Comment by ianlewis** [comment]
#3648 was merged so this should be fixed in the next release.

**Comment by chipzoller** [comment]
The community thanks you!
