### ISSUE TITLE
[feature] Support a configurable Rekor URL

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#372]
**Is your feature request related to a problem? Please describe.**
This will allow for people to configure a rekor URL for upload, which will mean we can configure verifier e2e tests to use rekor staging and avoid rate limiting.

**Describe the solution you'd like**
This should be defined as an input

- [ ] Go workflow
- [ ] Generic workflow
- [ ] Container workflow

**Comment by ianlewis** [comment]
This came up in #34 previously.

**Comment by ianlewis** [comment]
Created #387 to cover updating the e2e tests

**Comment by ianlewis** [comment]
Reopen to support in generic workflow

**Comment by ianlewis** [comment]
#391 Adds an option to configure the Rekor server address internally but we still need to support inputs to the workflows and a way to configure the TUF trust roots.

**Comment by ianlewis** [comment]
This issue is subsumed by #3607 which will cover all sigstore servers including Fulcio
