### ISSUE TITLE
[docs] Generate provenance for containers and store in ghcr.io

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#390]

**Comment by laurentsimon** [comment]
https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml can give some ideas.

We could even start by using the cosign CLI to sign the attestation as in https://github.com/laurentsimon/slsa-github-generator-ko/blob/main/.github/workflows/slsa3-builder.yml#L414

Do we want the verifier to support verification for the GA release?

**Comment by ianlewis** [comment]
Verifier support will be handled by https://github.com/slsa-framework/slsa-verifier/issues/92

**Comment by ianlewis** [comment]
The [workflow](https://github.com/slsa-framework/slsa-github-generator/blob/22155a9f17555d7df73d4374ad32e34e9cdb94d1/.github/workflows/generator_container_slsa3.yml) itself is implemented. Closing.
