### ISSUE TITLE
[feature] Use go code within the builder_go_slsa3.yml

### ISSUE THREAD

**Issue by naveensrinivasan** [slsa-framework/slsa-github-generator#398]
**Is your feature request related to a problem? Please describe.**
This https://github.com/slsa-framework/slsa-github-generator/blob/024238bc10cc620be603a7f5329be7a672171ba7/.github/workflows/builder_go_slsa3.yml#L15 has lots of shell script which is harder to maintain and harder to debug

**Describe the solution you'd like**

Use go code instead of using shell script. Another option is to use something like https://github.com/magefile/mage for doing this. Also `mage` has `0` dependencies.

**Comment by ianlewis** [comment]
I'd prefer not to use bash where it makes sense as well. I think the main issue with this is that we have to compile and run the code each run, it pretty hard for small snippets and increases the build times since Go compilation time isn't trivial. We've needed to reduce run time for #74 before.

I'm not totally sure about the builder workflows themselves but it might make sense for us to rewrite some of our [e2e tests](https://github.com/slsa-framework/example-package/tree/main/.github/workflows) in Go since much more extensive bash.

**Comment by laurentsimon** [comment]
+1 to what @ianlewis said.

We have https://github.com/slsa-framework/slsa-github-generator/issues/87, https://github.com/slsa-framework/slsa-github-generator/issues/26 that are related.

**Comment by ianlewis** [comment]
Yeah, it's a balance between
1. complexity - number of programming languages, libraries, coding styles etc.
2. reusability - ability to reuse code across actions/workflows
3. performance - need to compile, speed of action/workflow execution
4. security - attack surface, # and severity of potential bugs

As @laurentsimon said, I think the solution will not necessarily be just porting the existing scripts to Go but mostly creating reusable actions that are written in another language. That way it strikes a better balance with the concerns above. If we have that we can maybe just small snippets of bash and minimize the amount of code that we have to maintain.

**Comment by ianlewis** [comment]
Adding comments from PR #503
https://github.com/slsa-framework/slsa-github-generator/pull/503#issuecomment-1180617335
> > > @naveensrinivasan 
> > > After thinking about this should probably be written in `go`. This is adding tech debt.
> > 
> > @ianlewis 
> > Yeah, I'd like to reduce our use of inline shell scripts if we can too. Though it's pretty small so I could go either way.
> > I think installing Go compiler and compiling the program will add too much overhead to these kind of small actions. And we also really want to avoid having to do a checkout of the repository as part of the action as there are version skew and security implications.
> > If we want to write them in another language I think the best choice would probably be [writing it in Javascript](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action). It works similarly to the Dockerfile actions, but doesn't require building the image every time before running it.
> 
> @laurentsimon 
> I'm also leaning towards TS. On the other hand, the script is really small. I'm not even sure I'd call it "tech debt".

**Comment by laurentsimon** [comment]
The workflows now use common actions, so I think we can close this issue. Please re-open if needed. Thanks
