### ISSUE TITLE
[bug] Unhelpful error message when generator can not be fetched in generic workflow (due to using a non-released ref)

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa-github-generator#431]
**Describe the bug**
#86 introduced fetching the generator binary to speed up build times, however the fetch will always fail when not using a released version of the reusable action. That is, if I use the action `@main` and don't explicity opt in to compiling the generator my workflow runs fail with:
> Fetching the generator with ref: refs/heads/main
Invalid ref: refs/heads/main

This makes sense once you dig into it, but was surprising even as a user with some familiarity with how the project works.

**To Reproduce**

1. Create an action which includes the reusable workflow with a non-pinned ref: `uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main`
2. Inherit the default option of not compiling the generator `compile-generator: false`
3. Run the action
> Fetching the generator with ref: refs/heads/main
Invalid ref: refs/heads/main

**Expected behavior**
A meaningful error message which helps me to resolve the problem.

**Comment by joshuagl** [comment]
I think the current generator fetch logic won't succeed when the reusable workflow. is pinned by digest either?

**Comment by laurentsimon** [comment]
I updated the error msg as part of https://github.com/slsa-framework/slsa-github-generator/pull/438

**Comment by ianlewis** [comment]
This also affects the Go workflow FWIW

**Comment by ianlewis** [comment]
Are we ok with the error message change from #438 and can we close this? or do we need to do anything more?

**Comment by laurentsimon** [comment]
fine on my end, @joshuagl wdut?

**Comment by joshuagl** [comment]
I tried to provide some additional guidance on how to resolve this in #494
