### ISSUE TITLE
[feature] Be consistent in option names across builders

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#434]
The Go builder uses `upload-assets` and the generic one uses `upload-to-release`.

Let's try to be consistent across our builders. Wdut?

If everyone agrees to be consistent, what name shall we give this option?

/cc @ianlewis @joshuagl @asraa

**Comment by ianlewis** [comment]
I thought about it a bit but I changed it since I wasn't uploading assets per se (just provenance). I don't feel strongly so ok with going with `upload-assets` though.

**Comment by laurentsimon** [comment]
I think we called the option `upload-assets` because they appear under `assets` in the release https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.1.1

Did you mean something more specific by "assets"?
