### ISSUE TITLE
[bug] Builders broken

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#452]
I broke the builders in my series of PRs where I introduced the component Actions.
Main problem is that we don't checkout the re-usable workflow before calling the internal Actions, so the Actions calls are failing.

I think we need to pin it to a good sha using `slsa-framework/.github/actions/name@sha1`, like we do for the detect-ref Action.

An alternative solution would be to checkout the re-usable workflow, but that's cumbersome and may complicate the code in order to avoid interference between the re-usable workflow/project we're building.. so seems prone to mistakes

Will tackle this tmr.

**Comment by ianlewis** [comment]
I took a stab at this in #453. Unfortunately it looks like we still need to do the checkout even if we use `slsa-framework/.github/actions/name@sha1`

I think `detect-workflow` works without a checkout simply because we use a `Dockerfile` for that action.

**Comment by ianlewis** [comment]
@laurentsimon 

#454 Updates the actions themselves to reference each other by sha. We need to disable pre-submit requirements for this to go in.

#453 This restores the pre-submits but workflows need to be updated with the right git sha after #454 is merged.

I added notes to each PR so that hopefully everything is clear.

**Comment by laurentsimon** [comment]
Thank you @ianlewis , much appreciated.
I'll send a PR documenting how to handle Action

**Comment by laurentsimon** [comment]
Actively working non fixing this. Will be a series of PRs

**Comment by laurentsimon** [comment]
so:
- [ ] Ony inline scripts
- [ ] Fix typos
- [ ] Create a secure-upload-artifact Action
- [ ] Create README.md for Action development
- [ ] Create pre-submit to validate the README guidelines

**Comment by laurentsimon** [comment]
This done. Closing
