### ISSUE TITLE
[docs] Verification with sigstore-policy-controller

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#491]
Document examples using [sigstore-policy-controller](https://docs.sigstore.dev/policy-controller/overview) to verify provenance.

**Comment by laurentsimon** [comment]
There's also https://github.com/sigstore/cosign-gatekeeper-provider for gatekeeper, but it seems the gatekeeper's feature is in alpha mode.

/cc @developer-guy (maintainer for the repo above)
