### ISSUE TITLE
[feature] randomize binary names

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#500]
We currently use hard-coded names for builder binaries and project binaries we compile. This has some downsides:
1. If a user calls our builder multiple times in the same workflow, they will need to make the build sequential or it will likely fail. (I've seen one user do this already)
2. If user uses multiple builder calls in the same workflow, the workflow will race to download the binary and it could be corrupt and the run will fail
3. If the generated binary is the same as a file in the repo, it could overwrite it. (not sure if this could lead to problems or not)

So I propose randomizing the names of the generated binaries. Anyone OK with that?

I will add an e2e tests as well.

**Comment by ianlewis** [comment]
I think randomizing the names will be the simplest approach.

I think that the user will use the outputs to determine the right file name for each individual run, right?

**Comment by laurentsimon** [comment]
Internally, we'll use random names. The final output will still be determined by the developer. For example, in the case of Go builders, the .slsa-goreleaser defines the output name.

You're right, the developer can still use the `outputs` field.

**Comment by ianlewis** [comment]
SG. I think the generic workflow will need a way to either set the name of the provenance file or randomize the name since it currently uses a static name.

**Comment by laurentsimon** [comment]
Done. Closing

**Comment by laurentsimon** [comment]
Re-opening because @ianlewis is write about generic workflow attestation name.

**Comment by laurentsimon** [comment]
Something to add is presubmits to test multiple runs of the builders.

**Comment by laurentsimon** [comment]
I added support for randomized builder binaries for the generic workflow. Last AI is to add a pre-submit if we think it's necessary

**Comment by ianlewis** [comment]
> I added support for randomized builder binaries for the generic workflow. Last AI is to add a pre-submit if we think it's necessary

What would you test in the pre-submit? Maybe failure if two calls to the workflow have the same attestation-name?

**Comment by ianlewis** [comment]
Hmm. `actions/upload-artifact` doesn't have an option to fail if the artifact already exists so two calls to the generic workflow with the same attestation-name will clobber each other.
https://github.com/slsa-framework/slsa-github-generator/actions/runs/2716814219

**Comment by laurentsimon** [comment]
Good catch. We rely on the user to give to provide non-colliding names for the result. The attestations overwrite each other, but the verification will fail for one of the artifacts, so we fail close ,not open. 

My original suggestion was to use a workflow similar to https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic.schedule.main.multi-subjects.slsa3.yml to catch errors early.

**Comment by ianlewis** [comment]
I added some tests in https://github.com/slsa-framework/example-package/pull/90

Do you think that will be enough?

**Comment by laurentsimon** [comment]
definitely.

**Comment by ianlewis** [comment]
Tests in https://github.com/slsa-framework/example-package/pull/90 were merged and ran successfully.
