### ISSUE TITLE
[e2e]: go tag main adversarial-asset-binary slsa3 

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#537]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.64
Run: https://github.com/slsa-framework/example-package/actions/runs/2661149407
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.64
Date: Wed Jul 13 05:17:07 UTC 2022

**Comment by laurentsimon** [comment]
I'll disable the adversarial tests about assets, since they are too flaky and don't add much value.

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.65
Run: https://github.com/slsa-framework/example-package/actions/runs/2668112374
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.65
Date: Thu Jul 14 05:26:42 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.66
Run: https://github.com/slsa-framework/example-package/actions/runs/2674842625
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.66
Date: Fri Jul 15 05:40:45 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.67
Run: https://github.com/slsa-framework/example-package/actions/runs/2680730190
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.67
Date: Sat Jul 16 05:11:32 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.68
Run: https://github.com/slsa-framework/example-package/actions/runs/2684330498
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.68
Date: Sun Jul 17 05:14:49 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.69
Run: https://github.com/slsa-framework/example-package/actions/runs/2688315059
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.69
Date: Mon Jul 18 05:27:05 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.70
Run: https://github.com/slsa-framework/example-package/actions/runs/2695382153
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.70
Date: Tue Jul 19 05:44:14 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.71
Run: https://github.com/slsa-framework/example-package/actions/runs/2702408296
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.71
Date: Wed Jul 20 05:22:04 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.72
Run: https://github.com/slsa-framework/example-package/actions/runs/2709497830
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.72
Date: Thu Jul 21 05:26:58 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.73
Run: https://github.com/slsa-framework/example-package/actions/runs/2716479924
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.73
Date: Fri Jul 22 05:23:25 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.74
Run: https://github.com/slsa-framework/example-package/actions/runs/2722551786
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.74
Date: Sat Jul 23 05:15:03 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.75
Run: https://github.com/slsa-framework/example-package/actions/runs/2726099142
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.75
Date: Sun Jul 24 05:16:03 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.76
Run: https://github.com/slsa-framework/example-package/actions/runs/2730061624
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.76
Date: Mon Jul 25 05:25:16 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.77
Run: https://github.com/slsa-framework/example-package/actions/runs/2737217716
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.77
Date: Tue Jul 26 05:38:33 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.78
Run: https://github.com/slsa-framework/example-package/actions/runs/2744344164
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.78
Date: Wed Jul 27 05:28:43 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.79
Run: https://github.com/slsa-framework/example-package/actions/runs/2751476792
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.79
Date: Thu Jul 28 05:23:14 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.80
Run: https://github.com/slsa-framework/example-package/actions/runs/2758512322
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.80
Date: Fri Jul 29 05:25:48 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.81
Run: https://github.com/slsa-framework/example-package/actions/runs/2764675311
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.81
Date: Sat Jul 30 05:17:04 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.82
Run: https://github.com/slsa-framework/example-package/actions/runs/2768309456
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.82
Date: Sun Jul 31 05:14:44 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.83
Run: https://github.com/slsa-framework/example-package/actions/runs/2772543442
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.83
Date: Mon Aug  1 05:51:24 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.84
Run: https://github.com/slsa-framework/example-package/actions/runs/2779834872
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.84
Date: Tue Aug  2 05:42:45 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.85
Run: https://github.com/slsa-framework/example-package/actions/runs/2787116671
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.85
Date: Wed Aug  3 05:40:07 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.86
Run: https://github.com/slsa-framework/example-package/actions/runs/2794338289
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.86
Date: Thu Aug  4 05:27:25 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.87
Run: https://github.com/slsa-framework/example-package/actions/runs/2801454718
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.87
Date: Fri Aug  5 05:29:02 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.88
Run: https://github.com/slsa-framework/example-package/actions/runs/2807705889
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.88
Date: Sat Aug  6 05:07:11 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.89
Run: https://github.com/slsa-framework/example-package/actions/runs/2811420493
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.89
Date: Sun Aug  7 05:07:55 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.90
Run: https://github.com/slsa-framework/example-package/actions/runs/2815555176
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.90
Date: Mon Aug  8 05:18:37 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.91
Run: https://github.com/slsa-framework/example-package/actions/runs/2822892833
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.91
Date: Tue Aug  9 05:21:19 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.92
Run: https://github.com/slsa-framework/example-package/actions/runs/2830167654
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.92
Date: Wed Aug 10 05:08:36 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.93
Run: https://github.com/slsa-framework/example-package/actions/runs/2837521257
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.93
Date: Thu Aug 11 05:11:56 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.94
Run: https://github.com/slsa-framework/example-package/actions/runs/2844601172
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.94
Date: Fri Aug 12 05:13:46 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.95
Run: https://github.com/slsa-framework/example-package/actions/runs/2850802141
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.95
Date: Sat Aug 13 05:08:45 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.96
Run: https://github.com/slsa-framework/example-package/actions/runs/2854552392
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.96
Date: Sun Aug 14 05:12:26 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.97
Run: https://github.com/slsa-framework/example-package/actions/runs/2858654504
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.97
Date: Mon Aug 15 05:36:12 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.98
Run: https://github.com/slsa-framework/example-package/actions/runs/2865424702
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.98
Date: Tue Aug 16 05:17:22 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.99
Run: https://github.com/slsa-framework/example-package/actions/runs/2872993710
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.99
Date: Wed Aug 17 05:40:20 UTC 2022

**Comment by laurentsimon** [comment]
Repo: https://github.com/slsa-framework/example-package/tree/v12.0.100
Run: https://github.com/slsa-framework/example-package/actions/runs/2880147138
Workflow file: https://github.com/slsa-framework/example-package/tree/main/.github/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Workflow runs: https://github.com/slsa-framework/example-package/actions/workflows/e2e.go.tag.main.adversarial-asset-binary.slsa3.yml
Trigger: push
Branch: v12.0.100
Date: Thu Aug 18 05:34:24 UTC 2022

**Comment by ianlewis** [comment]
I disabled this test for now. See #960
