### ISSUE TITLE
[release] Generic generator

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#544]
We plan to release the generic generator for non-container artifact next week. This will be a "silent" release. Once it's is released, we will reach out to individual repositories via issues / PRs for adoption, in order to gather early feedback.

Task to complete for the release:
- [X] E2e 2 hash verification verify; done except the asset which we plan to disable
- [x] Test data on verifier https://github.com/slsa-framework/slsa-verifier/issues/133 @asraa will handle this
- [x] E2e tests for multiple calls to the generic builder https://github.com/slsa-framework/example-package/actions/runs/2679093902
- [x] E2e tests for multiple calls to the Go builder https://github.com/slsa-framework/example-package/actions/runs/2679105904
- [x] Option to set the name of the attestation https://github.com/slsa-framework/slsa-github-generator/pull/545
- [x] E2e test for wrong subject for generic workflow, see [e2e.generic.schedule.main.adversarial-invalidsubjects.slsa3.yml](https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic.schedule.main.adversarial-invalidsubjects.slsa3.yml)
- [x] E2e tests for adversarial attestation path see [e2e.generic.schedule.main.adversarial-invalidpath.slsa3.yml](https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic.schedule.main.adversarial-invalidpath.slsa3.yml). 
- [x] Fix pre-submits https://github.com/slsa-framework/slsa-github-generator/pull/549
- [x] Example for Java / Maven in https://github.com/slsa-framework/slsa-github-generator/pull/556 @loosebazooka will take care of it, thank you!

I'll take a stab at these. If you want to help, let me know.

Later, we will have a proper announcement with blog post, maybe combining the work on generic containers.

/cc @ianlewis @asraa @joshuagl

**Comment by laurentsimon** [comment]
I finished the items on the list.

**Comment by ianlewis** [comment]
All of the tasks listed above are complete so I think we can close the issue.
