### ISSUE TITLE
Docker build image workflow

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#56]
Based on #23 it would be possible to allow the use of a generic Docker image to perform the build step prior to provenance generation.

Considerations:
- We could allow users to specify a publicly or privately available Docker image by name and run that.
- We could allow users to specify a Dockerfile which we build for them before running the image.

**Comment by rbehjati** [comment]
Can this be closed and marked as completed now that we have the container-based builder?

**Comment by asraa** [comment]
I think so - the second suggestion about provenance for a docker file is specified here: https://github.com/slsa-framework/slsa-github-generator/issues/57
