### ISSUE TITLE
[bug] Verifying multiple artifacts from a single provenance doc

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#609]
`slsa-verifier` doesn't seem to support when there are multiple artifacts in the same provenance doc. I would have expected it to work if I had something like the following subject:

```shell
$ jq -r '.payload' < attestation.intoto.jsonl | base64 -d | jq '.subject'
[
  {
    "name": "artifact1",
    "digest": {
      "sha256": "b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c"
    }
  },
  {
    "name": "artifact2",
    "digest": {
      "sha256": "7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730"
    }
  }
]
```

and this configSource:

```shell
$ jq -r '.payload' < attestation.intoto.jsonl | base64 -d | jq '.predicate.invocation.configSource'
{
  "uri": "git+https://github.com/ianlewis/actions-test@refs/tags/v0.0.39",
  "digest": {
    "sha1": "6ecfa9f9f837975f6a03012044b95c612f0d7324"
  },
  "entryPoint": ".github/workflows/provenance-only.yml"
}
```

... created by [this workflow](https://github.com/ianlewis/actions-test/blob/6ecfa9f9f837975f6a03012044b95c612f0d7324/.github/workflows/provenance-only.yml), then I could call slsa-verifier twice. Once for each artifact but it doesn't work.

```shell
$ sha256sum artifact1 artifact2
b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c  artifact1
7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730  artifact2

$ slsa-verifier -provenance attestation.intoto.jsonl -tag v0.0.39 -artifact-path artifact1 -source github.com/ianlewis/actions-test
verification failed: could not find a matching valid signature entry

$ slsa-verifier -provenance attestation.intoto.jsonl -tag v0.0.39 -artifact-path artifact2 -source github.com/ianlewis/actions-test
verification failed: could not find a matching valid signature entry
```

I know that the [artifact sha256 is used to look up the signature entry](https://github.com/slsa-framework/slsa-verifier/blob/562cb8410dd056817767af858f6ae79d66c05580/pkg/rekor.go#L258-L273) in rekor but I'm not sure [how this index is actually created by the builder](https://github.com/slsa-framework/slsa-github-generator/blob/1a55da84338004ca26d38b941483c89ab93a695d/signing/sigstore/rekor.go#L61-L93).

Not sure if this is an issue that needs to be fixed here or in the verifier so tracking it here for now.

/cc @laurentsimon @asraa

**Comment by ianlewis** [comment]
Here's the full attestation from my test: [attestation.intoto.jsonl.zip](https://github.com/slsa-framework/slsa-github-generator/files/9165106/attestation.intoto.jsonl.zip)

**Comment by asraa** [comment]
Taking a look now. FYI 

> I know that the [artifact sha256 is used to look up the signature entry](https://github.com/slsa-framework/slsa-verifier/blob/562cb8410dd056817767af858f6ae79d66c05580/pkg/rekor.go#L258-L273) in rekor but I'm not sure [how this index is actually created by the builder](https://github.com/slsa-framework/slsa-github-generator/blob/1a55da84338004ca26d38b941483c89ab93a695d/signing/sigstore/rekor.go#L61-L93).

We moved away from using the artifact digest to lookup in Rekor. That uses the (unreliable) index that Rekor populates, and now, for backwards compatibility, we leave that in as a fallback mechanism with old builders.

New builders can query directly for the Rekor entry because they have the full information that went into the entry leaf. The entry includes the certificate, which we now stick into the signature:
```
$ cat ~/Downloads/attestation.intoto.jsonl  | jq -r '.signatures'
[
  {
    "keyid": "",
    "sig": "MEQCIF6oPSpgnVffc+BEtc16OZIZ21Avvg/a/dV206Bucl+fAiBmVgkU0I5yzdXk7QA/xiBoyKYUHraVd5RtgtLI8AapYA==",
    "cert": "-----BEGIN CERTIFICATE-----\nMIIDQTCCAsagAwIBAgITfWbcneiTU8esDUaZWtXJVDlkNjAKBggqhkjOPQQDAzAq\nMRUwEwYDVQQKEwxzaWdzdG9yZS5kZXYxETAPBgNVBAMTCHNpZ3N0b3JlMB4XDTIy\nMDcyMjA1MzAxMFoXDTIyMDcyMjA1NDAwOVowADBZMBMGByqGSM49AgEGCCqGSM49\nAwEHA0IABBMUyVDScBr0hGjWwOG8YHl5mtuJsdyvdUxLO2WpdeOcqs4lvNU1P1T7\nRCLWwF1HwvRBPCUYrC/DPtKXwsiUnF+jggHzMIIB7zAOBgNVHQ8BAf8EBAMCB4Aw\nEwYDVR0lBAwwCgYIKwYBBQUHAwMwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUjhw+\nq2g3EqDuTAm3cm7x4GXeCXgwHwYDVR0jBBgwFoAUWMAeX5FFpWapesyQoZMi0CrF\nxfowgYgGA1UdEQEB/wR+MHyGemh0dHBzOi8vZ2l0aHViLmNvbS9pYW5sZXdpcy9z\nbHNhLWdpdGh1Yi1nZW5lcmF0b3IvLmdpdGh1Yi93b3JrZmxvd3MvZ2VuZXJhdG9y\nX2dlbmVyaWNfc2xzYTMueW1sQHJlZnMvaGVhZHMvZ2VuZXJpYy1yZWxlYXNlMCIG\nCisGAQQBg78wAQQEFFNMU0EgcHJvdmVuYW5jZSBvbmx5MBIGCisGAQQBg78wAQIE\nBHB1c2gwNgYKKwYBBAGDvzABAwQoNmVjZmE5ZjlmODM3OTc1ZjZhMDMwMTIwNDRi\nOTVjNjEyZjBkNzMyNDAjBgorBgEEAYO/MAEFBBVpYW5sZXdpcy9hY3Rpb25zLXRl\nc3QwOQYKKwYBBAGDvzABAQQraHR0cHM6Ly90b2tlbi5hY3Rpb25zLmdpdGh1YnVz\nZXJjb250ZW50LmNvbTAfBgorBgEEAYO/MAEGBBFyZWZzL3RhZ3MvdjAuMC4zOTAK\nBggqhkjOPQQDAwNpADBmAjEAkRtZ15fWNS0rqPR8GxpPnbOkaqy90s0/6PrgVCtr\n8yu7yqALoPaUvWNP6yiW106+AjEAoC3YPemsYfcviuKuLiK/1stPeCOYJftzLbov\nvzxSGqm6RZFPEZz/0AOxI1LWIJ12\n-----END CERTIFICATE-----\n"
  }
]
```

**Comment by asraa** [comment]
This is good timing because I had a draft PR staged to test multiple subjects for the builders v1.2.0+!

**Comment by asraa** [comment]
What version are you running? This is what I get running from main:

```
$ go run . -provenance ~/Downloads/attestation.intoto.jsonl -tag v0.0.39 -artifact-path ~/Downloads/artifact1 -source github.com/ianlewis/actions-test
Verified signature against tlog entry index 3005870 at URL: https://rekor.sigstore.dev/api/v1/log/entries/20dd86229de1b49db76d6eb0d84ce1ff17dfb7cfee70d2cf422512900c32595c
Signing certificate information:
 {
	"caller": "ianlewis/actions-test",
	"commit": "6ecfa9f9f837975f6a03012044b95c612f0d7324",
	"job_workflow_ref": "/ianlewis/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/heads/generic-release",
	"trigger": "push",
	"issuer": "https://token.actions.githubusercontent.com"
}
FAILED: SLSA verification failed: untrusted reusable workflow: ianlewis/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml
exit status 2
```

We haven't cut a release with support for multi subject yet, we will after I submit exactly this test PR.

**Comment by laurentsimon** [comment]
I expect multiple artifacts to work. We have e2e tests for it as well https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic.schedule.main.multi-subjects.slsa3.yml

**Comment by ianlewis** [comment]
> What version are you running?

I was using the verifier from the latest release (v1.0.2) rather than HEAD so that might be it.

**Comment by ianlewis** [comment]
I verified it was able to verify the signature using head so I'll go ahead and close this. I guess I just expected that it was working earlier than the last release.

```
$ go run . -provenance ~/tmp/attestation.intoto.jsonl -tag v0.0.39 -artifact-path ~/tmp/artifact1 -source github.com/ianlewis/actions-test
Verified signature against tlog entry index 3005870 at URL: https://rekor.sigstore.dev/api/v1/log/entries/20dd86229de1b49db76d6eb0d84ce1ff17dfb7cfee70d2cf422512900c32595c
FAILED: SLSA verification failed: untrusted reusable workflow: ianlewis/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml
exit status 2

$ go run . -provenance ~/tmp/attestation.intoto.jsonl -tag v0.0.39 -artifact-path ~/tmp/artifact2 -source github.com/ianlewis/actions-test
Verified signature against tlog entry index 3005870 at URL: https://rekor.sigstore.dev/api/v1/log/entries/20dd86229de1b49db76d6eb0d84ce1ff17dfb7cfee70d2cf422512900c32595c
FAILED: SLSA verification failed: untrusted reusable workflow: ianlewis/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml
exit status 2
```
