### ISSUE TITLE
Re-organize docs

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#62]
We need to organize docs by workflow.

- README.md - base readme for the project. Links to docs for individual workflows
  - builders/go/README.md - Doc for Go builder.
  - builders/slsa/README.md - Doc for provenance-only workflow
  - etc.

**Comment by laurentsimon** [comment]
We also need to document the release process in a RELEASE.md. See https://github.com/slsa-framework/slsa-github-generator/issues/74
