### ISSUE TITLE
[feature] Update generic builder type

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#627]
The Go builder type has:
```
"buildType": "https://github.com/slsa-framework/slsa-github-generator/go@v1",
```

the generic generator ahs:
```
"buildType": "https://github.com/slsa-framework/slsa-github-generator@v1",
```

I'm not sure this is consistent. Should the latter be `https://github.com/slsa-framework/slsa-github-generator/generic@v1`?

Or maybe we should keep `https://github.com/slsa-framework/slsa-github-generator@v1` for all of them, since the builder name is available anyway?

/cc @ianlewis

**Comment by ianlewis** [comment]
Yeah, I think ` https://github.com/slsa-framework/slsa-github-generator/generic@v1` is more consistent since it fits into a ` https://github.com/slsa-framework/slsa-github-generator/<builder-name>@v1` pattern.
