### ISSUE TITLE
[feature] Rename attestation.intoto.jsonl to provenance.intoto.jsonl

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#654]
Shall we rename the default provenance filename for the generic workflows?

Maybe slsa3-provenance.intoto.jsonl or simply provenance.intoto.jsonl?

@ianlewis wdut?

**Comment by ianlewis** [comment]
Yeah, maybe that makes more sense.

**Comment by ianlewis** [comment]
BTW, the [in-toto attestation doc](https://github.com/in-toto/attestation/blob/main/spec/bundle.md#file-naming-convention) states:

* Bundles that concern a single artifact SHOULD name the bundle file `<artifact filename>.intoto.jsonl`.
* Bundles that concern multiple artifacts SHOULD name the bundle file `multiple.intoto.jsonl`.

So maybe we should be adhering to this as the default file names.

**Comment by laurentsimon** [comment]
LGTM.
