### ISSUE TITLE
Feature: automated update of builder's API

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#67]
Our builders need to use the API of https://github.com/slsa-framework/slsa-github-generator at HEAD.
This means every time we make an update to the generic API, we need to update the builder's go.sum/mod

I don't think we can check for it in pre-submits, because the hash to update to is unknown until the commit is pushed to main.

I think we have the following options:
1. Figure out how to configure dependabot to send us PR
2. Write our own schedule-trigger workflows once every X days to create an PR.

Note that this may quickly become an endless cycle if we're not careful: each new commit will create a new HEAD, which would trigger a new PR, etc. We may want to send a PR *only* if the code of the generic API has changed.

**Comment by ianlewis** [comment]
I added #66 to consider using Go workspaces. That should allow us to not have to deal with constantly updating as long as it's in the same workspace, but I haven't tried to use it much yet.

**Comment by laurentsimon** [comment]
If workspaces work, certainly a better way that what I'm proposing here. Thanks for the link!

**Comment by ianlewis** [comment]
BTW, is it necessary to have a separate `go.mod` for each builder? what benefit does it actually give us if we're in the same repo? Currently we don't have one for provenance-only and I'm wondering if we should add one, or if maybe removing the one for the go builder is possible way to solve the issue.

**Comment by laurentsimon** [comment]
I think the original idea was to have each builder separate so that they have their own dependencies, and not the cumulative sum of all builder's dependencies. I'm not sure the dependencies for each builder will be different in practice, so it may be ok to share the the same go.mod?

Another reason was to keep them private. I think we can achieve via `internal/`, right?

**Comment by ianlewis** [comment]
`internal/` should keep folks from importing it directly but it'll still get included.
