### ISSUE TITLE
Which ecosystem to target next? (please vote)

### ISSUE THREAD

**Issue by joshuagl** [slsa-framework/slsa-github-generator#687]
The team are looking for the right ecosystem to target next and build a level 3 builder for. Please use this issue to vote for the ecosystem you care about.

We'll use comments and reactions to gauge interest.

* Please use a comment per ecosystem
* If a comment **does not exist** for the ecosystem you think we should target, please add a comment with the ecosystem's name and add a thumbs up reaction.
* If a comment **does exist** for the ecosystem you would like us to target, please add a thumbs up reaction to that comment to indicate your vote.

**Comment by joshuagl** [comment]
Python

**Comment by joshuagl** [comment]
Java/Maven (see also #594)

**Comment by ianlewis** [comment]
containers (it's already on the roadmap but :shrug:)

**Comment by mlieberman85** [comment]
Rust

**Comment by shaunmlowry** [comment]
Ruby

**Comment by mihaimaruseac** [comment]
Haskell

**Comment by Foxboron** [comment]
Debian

**Comment by ianlewis** [comment]
We have ongoing plans for new workflows based on the [BYOB Framework](https://github.com/slsa-framework/slsa-github-generator/milestone/11)
- [Node packages](https://github.com/slsa-framework/slsa-github-generator/milestone/8) 
- [Java/Maven Builder](https://github.com/slsa-framework/slsa-github-generator/milestone/13)
- [Dockerfile builder](https://github.com/slsa-framework/slsa-github-generator/milestone/5)

I'll go ahead and close this issue and we can revisit priorities after the next quarter or so.
