### ISSUE TITLE
[feature] Add a release URL to builders and generators for uploading assets

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#710]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
For some workflow triggers like `workflow_dispatch`, the `github.ref` does not indicate the release URL. We should expose an option like 
```
          upload_url: ${{ steps.create-release.outputs.upload_url }}
```

that can be used to indicate the release URL to upload assets to.

That would simplify the workflow, and reduce the amount of friction for users. Otherwise, they need to specify their own upload, or manually upload the artifact themselves.

See https://github.com/GoogleContainerTools/jib/commit/e85d34e1661acf43ce078412719a2c2ce1a42f59

**Describe alternatives you've considered**

**Additional context**

**Comment by laurentsimon** [comment]
Repositories to update:
-[ ] https://github.com/GoogleContainerTools/jib/pull/3726

**Comment by laurentsimon** [comment]
We also need e2e tests for this.

**Comment by laurentsimon** [comment]
See this PR which has the code to use: https://github.com/GoogleContainerTools/jib/pull/3726/files

**Comment by ianlewis** [comment]
> See this PR which has the code to use: https://github.com/GoogleContainerTools/jib/pull/3726/files

This PR uses `actions/upload-release-asset` which isn't maintained anymore in favor of `softprops/action-gh-release` which is the action we use. Maybe the right input we need use is `tag_name`?
https://github.com/softprops/action-gh-release#inputs

**Comment by laurentsimon** [comment]
you're correct. Note that I only re-used the GHA they already use in their code, it's not something I asked them to use. 
I've created https://github.com/slsa-framework/slsa-github-generator/pull/713 to own the code for us internally, and maybe other repos could use it?

**Comment by hazcod** [comment]
Can you mention here what release it'll end up in @laurentsimon ? Thanks!

**Comment by laurentsimon** [comment]
Should be part of the `[2022 Stability improvements](https://github.com/slsa-framework/slsa-github-generator/milestone/6)`. Thanks for the interest! Which project do you want to use it for?

**Comment by hazcod** [comment]
> Should be part of the `[2022 Stability improvements](https://github.com/slsa-framework/slsa-github-generator/milestone/6)`. Thanks for the interest! Which project do you want to use it for?

Thanks! I'm writing an SDK for the API on Intigriti and want to ensure we do all of our due diligence.
