### ISSUE TITLE
[feature] Improve generating provenance from matrix build

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#732]
Currently it's difficult to determine the artifacts from a job using a [matrix strategy](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) because each run of the strategy overwrites outputs from the previous job run. This is important for the generic workflow because the user's workflow needs to generate the sha256sum of the outputs and use as input it into the reusable workflow. Currently we rely on using job inputs and outputs for security reasons as they cannot be modified between jobs.

Example of a job using a matrix strategy: https://github.com/hashicorp/terraform/blob/07225e0a61c6b097431e736c5bb910bca5674096/.github/workflows/build.yml#L148

Some more context and discussion: https://github.com/community/community/discussions/17245

**Comment by ianlewis** [comment]
I'm not sure we can actually do anything about this in the workflow itself. This is perhaps just a documentation issue.

**Comment by ianlewis** [comment]
One solution would be to just look look at the run's uploaded artifacts after the matrix has fully run, pull them and generate the sha256sum. However, we can't do that because they could have been modified after they were built and uploaded.

**Comment by laurentsimon** [comment]
Re-usable workflow don't support matrixes, so IFAIK the best is to have this in the documentation. I created https://github.com/slsa-framework/slsa-github-generator/issues/707 last week. (There's an example of workflow I created for adoption)

**Comment by ianlewis** [comment]
Right, Your examples look ok. I suppose the best thing to do is to have a separate step for each matrix entry with an `if`. That was suggested in the https://github.com/orgs/community/discussions/17245. In our case we also have to combine the outputs after the fact as well.

I think this issue is pretty much just a duplicate of #707 so I'll close it and we can track there.
