### ISSUE TITLE
[bug] Certificates signed by unknown authority

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-github-generator#762]
**Describe the bug**
The `verify` job is failing with the following error:
```
$ go run . -artifact-path ~/Downloads/binary-linux-amd64 -provenance ~/Downloads/binary-linux-amd64.intoto.jsonl -source github.com/slsa-framework/example-package
got uuid x509: certificate signed by unknown authority
verification failed: could not find a matching valid signature entry
```

which may be related to the new endpoint. Investigating
@laurentsimon 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by laurentsimon** [comment]
Thanks @asraa!
/cc'ing @bobcallaway in case he has some ideas / pointers

**Comment by asraa** [comment]
Figured it out.

I guess at some point (not sure why it wasn't caught before) intermediates became necessary. Adding the fix. I will put out a patch release for v1.0 - v1.3

**Comment by asraa** [comment]
This should be fixed in the patches linked above!
