### ISSUE TITLE
[bug] Tests exit successfully even if unit tests fail

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#771]
**Describe the bug**
The golang builder makes an [Exec syscall directly](https://github.com/slsa-framework/slsa-github-generator/blob/c565ad10f0c2efdc6fcc8fe55b52845f85014dfa/internal/builders/go/pkg/build.go#L164). This causes tests that call `GoBuild.Run` to cause the test runner to exit prematurely as the original test runner's process context is overwritten.

Currently, even if tests fail the process executed Exec syscall returns successfully so no error code is returned and `go test` exits successfully. This masks unit test errors and is highly unintuitive.

**To Reproduce**
Create a failing test and run `go test -v ./...`

**Comment by laurentsimon** [comment]
great catch! Do you know if there's a way to force running the tests each in their own process?

**Comment by ianlewis** [comment]
I don't know if there is really unless we start our own separate processes. I think the real thing we should do is refactor the Go builder to fork/exec instead as that is generally much more intuitive.

**Comment by laurentsimon** [comment]
SG. You have a PR about this, let me know when you need review. Fyi, your PR will also be very useful for the npm builder because it requires running multiple commands. So I'm happy to help getting this PR through :)

**Comment by ianlewis** [comment]
Ah, yes #632 is related. Perhaps I'll take that off the back burner soon as that would be the proper solution.

#772 disables the offending test and will at least allow us to catch failing tests in the meantime.
