### ISSUE TITLE
[feature] npm builder: filter arguments

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-github-generator#889]
Let's think about whether we need to filter out certain build arguments or not, like we do for the go builder.

**Comment by ianlewis** [comment]
> Let's think about whether we need to filter out certain build arguments or not, like we do for the go builder.

What do you mean?

**Comment by laurentsimon** [comment]
I meant arguments like `-exec`. AT the time this was an open question. This is not needed any more. Closing.
