### ISSUE TITLE
Feature: output public key certificate

### ISSUE THREAD

**Issue by loosebazooka** [slsa-framework/slsa-github-generator#95]
Public key certficiate should be saved with the intoto artifact. This gives us sufficient information to verify against rekor.

```
rekor-cli verify --artifact <artifact> --public-key <certificate> --type intoto
```

**Comment by ianlewis** [comment]
@laurentsimon @asraa @loosebazooka is this still valid? I think this would mostly be subsumed by offline verification work that we are tracking separately? Can we close this?

**Comment by asraa** [comment]
Yes, this is outdated, we currently do what Laurent described above.

You can use Rekor CLI to find the entry. For e.g. with slsa-verifier's release .intoto.jsonl

```
$ cat ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.signatures[0].cert' > cert.pem
$ rekor verify --artifact ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl --public-key cert.pem --type intoto:0.0.1 --pki-format x509 --signature ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl
```
