### ISSUE TITLE
[bug] second argument to errors.As should not be *error

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-github-generator#969]
This message pops up when running unit tests.
```
github/oidc_test.go:237:10: second argument to errors.As should not be *error
```

**Comment by asraa** [comment]
Is this just a transient error? (From the rate limiting issue?)

I tried a couple of re-runs, but haven't hit it yet

**Comment by ianlewis** [comment]
This isn't an error per se as it doesn't stop and it's not an error in the Rekor client or anything so it shouldn't be any thing with rate limiting. It's just a log message that I think the stdlib spits out. It happens in tests and I'm not totally sure but I'm pretty sure it's not transient. I think it's just some test code that calls `errors.As` on an error pointer.

**Comment by ianlewis** [comment]
I found the issue. It only happens on Go 1.19+ and strangely it only seems to happen in the one file `oidc_test.go`. Other test files use the same code and types but don't produce this error message. I'm not sure why.

**Comment by ianlewis** [comment]
Related to:
- #782
- #970
